### ISSUE TITLE
(Bug) Mouse clicking/dragging adds an offset in 0.6.0-rc0

### ISSUE THREAD

**Issue by Manghi** [ggez/ggez#883] opened 2021-01-29 06:18 UTC
Props to @AaronM04 for first finding this bug.

**Describe the bug**
Mouse events are offset proportionally to the distance from the top-left corner of the window. The closer you are to (0,0) the less the error in offset is. The farther away from (0,0) in both positive directions increases the error.

**To Reproduce**
Run the `input_test` example on the head of the development branch. When the rectangle is dragged close to (0,0), there is virtually little-to-no offset error. The farther (+,+) you drag the rectangle to, the large the offset error is.

**Expected behavior**
The top-left corner of the rectangle follows the cursor on click/drag without an introduced offset.

**Screenshots or pasted code**
N/A but I was able to narrow down the offending commits these two back in Nov 2020:
```
The first bad commit could be any of:
599ab16bcd25e8db5a8c3fc8ab5d286cb348201e
6299b0b71662d642435968a83dd527dd0f02fdbc
We cannot bisect more!
```

Commit 599ab16bcd25e8db5a8c3fc8ab5d286cb348201e has build errors but looks like only a change in dependencies (`gfx_window_glutin`). 
Commit 6299b0b71662d642435968a83dd527dd0f02fdbc runs incredibly slow on my machine but it but does exhibit the issue in question. 

I scanned the code changes for the two commits but nothing stood out as an obvious introduction of the bug. The `input_test.rs` drawing code didn't change, and the mouse event handlers all look reasonable. I suspect it might be a dependency issue? Perhaps someone who is more familiar with how ggez/gfx interface might be able to solve this faster than me. (@sapir since he/she worked on these changes.)

**Hardware and Software:**
 - ggez version: Current git devel branch or tag `0.6.0-rc0`
 - OS: Linux Ubuntu 18.04
 - Graphics card: Nvidia GTX 1080
 - Graphics card drivers: 
`Kernel driver in use: nvidia`
`Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia`

**Comment by PSteinhaus** [comment] 2021-01-29 12:03
Thanks for the info!
I just tested it and I think I found the reason for this behavior.
It occurs when there is a mismatch between logical and physical screen size. For example setting scale from 125% to 100% made everything work as expected for me on Windows 10.

Thanks for narrowing it down. I'll try to look into this today.
Probably all that's necessary is changing some function to use physical size instead of logical size.

**Comment by PSteinhaus** [comment] 2021-01-29 12:45
Hmm... it turns out that [the mouse coordinates not matching the logical mouse coordinates IS expected behavior](https://docs.rs/ggez/0.5.1/ggez/input/mouse/fn.position.html).

So it's even simpler, we just need to fix the example (still an somewhat important fix because examples should point things such as this out).

**Comment by AaronM04** [comment] 2021-01-29 19:25
@PSteinhaus I'm a little confused. How is it expected behavior? I ask because [our game](https://github.com/conwayste/conwayste) shows the same behavior with the `devel` branch of ggez (it's working in v0.5.1) as the example.

If a sprite is supposed to follow the mouse, how should that be achieved now?

**Comment by PSteinhaus** [comment] 2021-01-30 16:11
It is expected behavior, because the function giving you the mouse coordinates explicitly states, that it
> Uses strictly window-only coordinates [...] in pixels

Therefore you need to calculate the corresponding logical mouse coordinates yourself, for example by calling ```[screen_coordinates](https://docs.rs/ggez/0.5.1/ggez/graphics/fn.screen_coordinates.html)```, to get your current screen coordinate system. For simpler cases it should be enough to just divide the coordinates through the scale factor of your window (see: [the changed input example](https://github.com/ggez/ggez/pull/884/files)).

**Comment by PSteinhaus** [comment] 2021-01-31 15:13
I just realised that while it may be expected behavior to return physical coordinates there's still a bug in all of this:

The initial screen coordinate system should exactly match the physical size of the window (the inner size of the window that is).
This not being true IS a bug. I'll look into it momentarily.

**Comment by PSteinhaus** [comment] 2021-01-31 15:52
Ok I found it. The initial screen coordinate system is calculated wrongly. It sets it to the logical instead of the physical size. Easy to fix.

**Comment by PSteinhaus** [comment] 2021-01-31 21:29
Fixed in #884.
As soon as it gets merged your old code from 5.1 should work in 6.0 as well.

**Comment by Manghi** [comment] 2021-02-01 04:20
Okay that makes perfect sense, thank you @PSteinhaus  for responding so quickly and providing those additional explanations. We both appreciate it!

**Comment by PSteinhaus** [comment] 2021-02-01 11:00
Well thank you both for finding and reporting this bug! Unnecessary breaking changes between versions are never a nice thing to have.

Also questions like these are really useful to figure out where improvements in the docs might be necessary :)

**Comment by PSteinhaus** [comment] 2021-02-15 14:07
This can be closed.

**Closed** 2021-02-15 14:17 UTC
