### ISSUE TITLE
Can't build on latest (15aa15b03 2017-07-21) nightly

### ISSUE THREAD

**Issue by ozkriff** [ggez/ggez#112] opened 2017-07-22 05:11 UTC
sdl2 dep causes ICE:

```
   Compiling sdl2 v0.29.1
error: internal compiler error: /checkout/src/librustc/infer/mod.rs:573: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<CB as audio::AudioCallback>)),depth=0),Unimplemented)]` resolving bounds after type-checking

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.20.0-nightly (15aa15b03 2017-07-21) running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:437:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `sdl2`.

To learn more, run the command again with --verbose.

```

```
$ rustc -V
rustc 1.20.0-nightly (15aa15b03 2017-07-21)
```

**Comment by ozkriff** [comment] 2017-07-22 05:30
https://github.com/AngryLawyer/rust-sdl2/issues/686 reported to sdl2

**Comment by MaulingMonkey** [comment] 2017-07-22 05:31
Rust issue: https://github.com/rust-lang/rust/issues/43350

**Comment by icefoxen** [comment] 2017-07-22 15:29
Could someone please check whether this happens on sdl2 0.30?  ggez 0.3 is a version behind because 0.30 introduced API changes I didn't want to bother with this instant.

**Comment by ozkriff** [comment] 2017-07-22 15:40
```
$ grep version Cargo.toml
version = "0.30.0"
version = "0.1"
version = "0.30.0"
version = "1.0.*"
$ rustc -V
rustc 1.20.0-nightly (15aa15b03 2017-07-21)
$ c b
   Compiling sdl2 v0.30.0 (file:///home/ozkriff/zemeroth/rust-sdl2)
warning: Quasi-quoting might make incremental compilation very inefficient: (NtExpr(..), None)
   --> src/sdl2/video.rs:135:17
    |
135 |           #[doc = $doc]
    |                   ^^^^
...
233 | /     attrs! {
234 | |         (SDL_GL_RED_SIZE, set_red_size, red_size, u8,
235 | |             "the minimum number of bits for the red channel of the color buffer; defaults to 3"),
236 | |
...   |
295 | |             "requests sRGB capable visual; defaults to false (>= SDL 2.0.1)")
296 | |     }
    | |_____- in this macro invocation

.
.
.

error: internal compiler error: /checkout/src/librustc/infer/mod.rs:573: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<CB as audio::AudioCallback>)),depth=0),Unimplemented)]` resolving bounds after type-checking

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.20.0-nightly (15aa15b03 2017-07-21) running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:437:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `sdl2`.

To learn more, run the command again with --verbose.
```

**Comment by icefoxen** [comment] 2017-07-24 20:12
I really am not going to try to keep pace with every bug in nightly, but I guess this should get left open for informational purposes until the problem is resolved.

Now if it's a bug in beta that's preventing ggez from building, that's a bit more of a concern.  We should keep an eye out for those so we can, if necessary, lean on/help the compiler team fix the bug before it hits stable...

**Comment by ozkriff** [comment] 2017-07-25 06:32
What I see as a problem here is that user can't run `cargo clippy` on his project because of this.

**Comment by ozkriff** [comment] 2017-07-29 19:19
btw, everything should work fine now:

https://github.com/AngryLawyer/rust-sdl2/issues/686#issuecomment-318848279

**Comment by icefoxen** [comment] 2017-07-31 15:14
Confirmed the build now passes, closing.

**Closed by icefoxen** 2017-07-31 15:14 UTC
Labels: wontfix
