### ISSUE TITLE
Examples panic during init on linux 

### ISSUE THREAD

**Issue by rustrust** [ggez/ggez#830] opened 2020-10-15 14:01 UTC
This computer runs Ubuntu Linux 18.04 LTS, fully up to date on an Intel CPU and GPU system. This computer is able to run, for instance, gfx-rs examples without issue, including examples running on an OpenGL backend.

On the most recent version ( https://github.com/ggez/ggez/commit/4f4bdebff463881c36325c7e10520c9a4fd8f75c  ), when running the  05_astroblasto or spritebatch examples, I get this error:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/USERNAME/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/wayland/window.rs:290:56
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::panicking::panic
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:50
   3: winit::platform::platform::wayland::window::Window::get_current_monitor
   4: ggez::graphics::context::GraphicsContextGeneric<B>::set_window_mode
   5: ggez::graphics::context::GraphicsContextGeneric<ggez::graphics::GlBackendSpec>::new
   6: ggez::context::ContextBuilder::build
   7: _05_astroblasto::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by icefoxen** [comment] 2020-11-01 16:49
Looks like a duplicate of #579 , see that thread for a workaround.  :C

**Closed** 2020-12-22 02:30 UTC
Labels: Type-CODE, dependency bug, duplicate
