### ISSUE TITLE
graphics::get_screen_coordinates() does not return a well-formed Rect

### ISSUE THREAD

**Issue by jrdlph** [ggez/ggez#115] opened 2017-07-28 03:04 UTC
related to #93
The return value of `graphics::get_screen_coordinates()` does not respect the meaning of the fields of a `Rect`, so invoking `.top()`, `.bottom()`, `.point()`, etc  on the `Rect` returned will not give you what you are looking for. The `x` and `y` fields should either represent the center point of the display (as in the current implementation of `Rect`), or the implementation of `Rect` should change so that `x` and `y` represent the top/bottom left corner.

I think the litmus test should be that drawing this `Rect` should draw a rectangle that fills the viewport. This would make reasoning about other `Rect`s in relation to the viewport much simpler.

**Comment by icefoxen** [comment] 2017-07-29 20:44
Duplicate of #93

**Closed** 2017-07-30 22:57 UTC
