### ISSUE TITLE
Cannot set portrait dimensions for the window

### ISSUE THREAD

**Issue by TatriX** [ggez/ggez#175] opened 2017-10-04 11:34 UTC
When I'm setting
```rust
    let mut c = conf::Conf::new();
    c.window_width = 720.0;
    c.window_height = 1280.0;
```
I get the error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WindowError(SdlError("Couldn\'t find display mode match"))', /checkout/src/libcore/result.rs:906:4
```

**Comment by TakWolf** [comment] 2017-10-04 20:11
I think this is an error from SDL.
When you set width or height value more than your monitor device real size, it will cause this error.

My monitor is 1366 * 768. So if I set width = 1367 or  height = 769, it will cause "Couldn\'t find display mode match".

**Comment by TatriX** [comment] 2017-10-04 20:14
Ah, yeah, you are right.

**Comment by TatriX** [comment] 2017-10-04 20:20
If there is an easy way to scale the whole `ctx`?

**Comment by icefoxen** [comment] 2017-10-12 13:59
I need to investigate this more because I'm not sure how SDL handles it; I thought it might only let you to set the window size to one of the known full-screen modes or something silly like that, but I'm not sure.

I'm not sure what you mean by scale the whole `ctx`, but if you want to move the viewport around so the window is "looking" at a different spot in the coordinate system then you should use `set_screen_coordinates`.

**Comment by TatriX** [comment] 2017-10-12 14:09
I solved the issue like this:
```rust
    let screen_height = 1000;
    let screen_width = 9 * screen_height / 16;
    c.window_width = screen_width;
    c.window_height = screen_height;

    state.scale_factor = screen_height as f32 / HEIGHT;

    graphics::set_transform(ctx, Matrix4::new_scaling(state.scale_factor));
    graphics::apply_transformations(ctx).unwrap();
```

**Comment by termhn** [comment] 2017-10-12 23:57
Really you should probably be setting/transforming the projection matrix here rather than the transform matrix -- that is really meant for transforming images/other Drawables before drawing in theory (it is used in drawing `SpriteBatch`es). I hadn't really seen a use for directly editing the raw projection matrix before, but I'm going to submit a PR that will let you do so to have the same effect in a more proper fashion like so, as well as make `SpriteBatches` behave better with user model matrix changes:

```rust
    let screen_height = 1000;
    let screen_width = 9 * screen_height / 16;
    c.window_width = screen_width;
    c.window_height = screen_height;

    state.scale_factor = screen_height as f32 / HEIGHT;

    graphics::transform_projection(ctx, Matrix4::new_scaling(state.scale_factor));
    graphics::apply_transformations(ctx).unwrap();
```

**Comment by TatriX** [comment] 2017-10-13 06:13
Nice. As you can see I'm saving the `scale_factor`, because I need it later in mouse handler for collision detection:
```rust
        println!("Mouse button pressed: {:?}, x: {}, y: {}", button, x, y);
        let p = Point2::new(x as f32, y as f32) / self.scale_factor;
```
As you added `get_transform()` probably you could add a helper method to transform coordinates from screen-to-world and vice versa?

Also I'd like to explain *why* I'm using such method. I have my resources drawn for `1080x1920` (for mobiles). But It's inconvenient on the desktop, that's why I scale it down to `1000px` height.

I'm not sure that it's a proper way to do things, cause I had never done any mobile before.

**Comment by termhn** [comment] 2017-10-13 20:55
Uhhh I don't think this is really somewhere I could make a helper that would be generic to be useful in many cases. I could probably make a helper function to put a point only through the view matrix... this is basically what you are saying with the "screen" to "world" (or vice-versa) conversion... If the idea of your conversion here is to transform between those two things then maybe you want to set the view matrix instead of projection matrix. As of right now, the idea is that the user should probably be keeping track of this state, though.

Honestly, I think you might want to rethink the way you're doing this though... the mobile and desktop versions should more than likely be significantly different or exactly the same interface-wise IMO.

**Comment by icefoxen** [comment] 2017-12-22 23:31
Should be fixed now?  @TatriX is this still a problem?

**Comment by TatriX** [comment] 2017-12-23 07:41
I tried setting 1080x1920 on fullhd screen with `ggez 0.4.0-rc.1`
and I still get a panic
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WindowError(SdlError("Couldn\'t find display mode match"))', /checkout/src/libcore/result.rs:916:4
```
Probably it's not a big deal but maybe a better error message can be delivered to the user.

**Comment by icefoxen** [comment] 2017-12-23 14:06
Is this full-screen or windowed?  I assume windowed...

I'll play with it a bit more.

**Comment by TatriX** [comment] 2017-12-23 14:09
```rust
    let screen_height = 1920;
    let screen_width = 1080;

    let cb = ContextBuilder::new("easykana", "TatriX")
        .window_setup(conf::WindowSetup::default().title("Easy Kana!").samples(8).unwrap(),)
        .window_mode(conf::WindowMode::default().dimensions(screen_width, screen_height),);

    let ctx = &mut cb.add_resource_path("./resources").build().unwrap();

```

**Comment by icefoxen** [comment] 2018-03-12 07:28
Confirmed on Windows 10.  SDL just gets grumpy when you tell it to make a window with a dimension bigger than the screen.  :-(

**Closed by icefoxen** 2018-03-12 07:28 UTC
Labels: question
