### ISSUE TITLE
Panic when running the examples

### ISSUE THREAD

**Issue by Avishayy** [ggez/ggez#483] opened 2018-10-05 15:53 UTC
Hey,

I cloned the repo, ran `cargo run --example astroblasto`, finished compiling and this panic popped up:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: VideoError("glXSwapIntervalMESA failed")', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  10: astroblasto::main
             at examples/astroblasto.rs:618
  11: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  16: main
  17: __libc_start_main
  18: _start
```

The only output I got before the panic is `Adding path "/home/user/ggez/resources`.

I tried to run some other examples, the panic still persists. I thought that something might be wrong with my SDL2 libraries, so I cloned the rust-sdl2 crate and ran the examples there, which worked just fine.

I'm using Ubuntu 18.04 with stable Rust 1.29, any help is appreciated!

**Comment by iTZAvishay** [comment] 2018-10-05 16:42
```
~/ggez (master ✔) ᐅ glxinfo | grep '^[a-zA-Z]'
name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
server glx extensions:
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
client glx extensions:
GLX version: 1.4
GLX extensions:
Extended renderer info (GLX_MESA_query_renderer):
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: SVGA3D; build: RELEASE;  LLVM;
OpenGL core profile version string: 3.3 (Core Profile) Mesa 18.1.5
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.1 Mesa 18.1.5
OpenGL shading language version string: 1.40
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 18.1.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
```

I should have probably mentioned it before, Ubuntu is running as a VM through VMWare. My GPU is NVIDIA GeForce GTX 750 Ti. 

I bet VMWare simply does not use my GPU and this is the cause, not sure how I should go on to fix it.

**Comment by iTZAvishay** [comment] 2018-10-19 15:43
Unfortunately, here is the output from `logging`:
```
[2018-10-19 08:41:12][DEBUG][logging] I am logged!
[2018-10-19 08:41:12][INFO ][logging] I am too!
[2018-10-19 08:41:12][TRACE][logging] Creating ggez context.
[2018-10-19 08:41:12][TRACE][ggez::filesystem] Resources path: "/home/avishay/ggez/target/debug/examples/resources"
[2018-10-19 08:41:12][TRACE][ggez::filesystem] No resources zip file found
[2018-10-19 08:41:12][TRACE][ggez::filesystem] User-local data path: "/home/avishay/.local/share/logging"
[2018-10-19 08:41:12][TRACE][ggez::filesystem] User-local configuration path: "/home/avishay/.config/logging"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: VideoError("glXSwapIntervalMESA failed")', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by icefoxen** [comment] 2018-10-20 15:32
Not sure what exactly is up here, I think that it is offering GL 3.3 Core profile and GL 3.1 Compatibility profile? And then ggez is choosing the latter for some reason. Setting it to be more strict and more configurable is already on the to-do list, I'll try to get it sorted out soon and we can see if that helps.

Though if you're going from a fresh checkout on the master branch, that should already choose 3.2 Core by default. Hmmm.

What happens if you try to run examples from the devel branch? I expect the same result, but I'm curious.

**Comment by icefoxen** [comment] 2018-10-20 15:34
Oh, also try disabling vsync in the Conf object and see if that makes any difference...

**Comment by iTZAvishay** [comment] 2018-10-20 17:50
Apparently I haven't updated my master branch since cloning it at the time of making this post, after pulling and recompiling the results are the same for both the master and devel branches.

As for disabling vsync is the Conf object, could you guide me on how to do that for the `logging` example? I am completely unfamiliar with the code base here.

**Comment by icefoxen** [comment] 2018-10-20 18:57
No problem.  `logging.rs` in the master branch, around line 170 or so, we have:

```rust

    // This sets up `ggez` guts (including filesystem) and creates a window.
    let ctx = &mut ContextBuilder::new("logging", "ggez")
        .window_setup(
            WindowSetup::default()
                .title("Pretty console output!")
                .resizable(true),
        )
        .window_mode(WindowMode::default().dimensions(640, 480))
        .build()
.unwrap();
```

Switch it to:

```rust

    // This sets up `ggez` guts (including filesystem) and creates a window.
    let ctx = &mut ContextBuilder::new("logging", "ggez")
        .window_setup(
            WindowSetup::default()
                .title("Pretty console output!")
                .resizable(true),
        )
        .window_mode(
            WindowMode::default()
                .dimensions(640, 480)
                .vsync(false)
        )
        .build()
.unwrap();
```

**Comment by iTZAvishay** [comment] 2018-10-20 19:12
Identical output, sadly.

I guess I'll have to boot into the Ubuntu.

**Comment by IGBC** [comment] 2021-06-03 16:17
Someone needs to verify that this is still valid, as these are now nearly 4 years old. Also we don't use SDL2 anymore.

**Comment by IGBC** [comment] 2021-06-03 16:44
> Someone needs to verify that this is still valid, as these are now nearly 4 years old. Also we don't use SDL2 anymore.

OK just read the full history on this one. And it looks like a driver bug for the VMWare driver of all things. Not sure we officially support running in emulated graphics, and there's been no updates for a few years, and the core rendering stack has since been switched away from SDL2. So closing.

**Closed by IGBC** 2021-06-03 16:44 UTC
Labels: bug
