### ISSUE TITLE
`mouse_motion_event` provides incorrect delta values

### ISSUE THREAD

**Issue by Nemo157** [ggez/ggez#977] opened 2021-08-23 11:12 UTC
**Describe the bug**
The `dy` and `dy` parameters to `mouse_motion_event` are different to the actual delta since the last call.

**To Reproduce**
```rust
use ggez::{Context, ContextBuilder, GameError, GameResult, event::EventHandler};

fn main() {
    let (ctx, event_loop) =
       ContextBuilder::new("game_name", "author_name")
           .build()
           .unwrap();

    ggez::event::run(ctx, event_loop, MousePos(0.0, 0.0));
}

struct MousePos(f32, f32);

impl EventHandler<GameError> for MousePos {
    fn mouse_motion_event(&mut self, _ctx: &mut Context, x: f32, y: f32, dx: f32, dy: f32) {
        let delta = (x - self.0, y - self.1);
        *self = MousePos(x, y);
        println!("{delta:6?} == ({dx:6?}, {dy:6?}) = {eq}", delta=delta, dx=dx, dy=dy, eq=delta == (dx, dy));
    }

    fn update(&mut self, _ctx: &mut Context) -> GameResult<()> {
        Ok(())
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult<()> {
        ggez::graphics::present(ctx)
    }
}
```

**Expected behavior**
The calculated `delta` above and the `(dx, dy)` provided are the same.

**Actual behavior**
The `(dx, dy)` provided are mostly far smaller than the actual value (though sometimes they're larger):

```
( -25.0,   -4.0) == (  -4.0,    0.0) = false
( -17.0,   -2.0) == (  -1.0,    0.0) = false
(  -2.0,    0.0) == (  -3.0,   -1.0) = false
( -11.0,   -3.0) == (  -1.0,    0.0) = false
( -10.0,   -2.0) == (  -1.0,    0.0) = false
(  76.0,   -3.0) == (   6.0,    0.0) = false
(  95.0,   -1.0) == (   6.0,    0.0) = false
( 108.0,   -2.0) == (   7.0,   -1.0) = false
(   6.0,    0.0) == (   7.0,    0.0) = false
```

**Hardware and Software:**
 - ggez version: Tested on 0.6 and `devel#0e335821`, an equivalent program on 0.5 also reports different values, but there I think it's biased towards just slightly overreporting the delta instead of massively underreporting it.
 - OS: Windows 10 Build 19043
 - Graphics card: NVidia RTX 2070 Super
 - Graphics card drivers: Vendor

**Comment by PSteinhaus** [comment] 2021-08-23 19:14
Thanks for reporting!

I just tried it out and now I wish I had acted on that nagging feeling that something is off with the mouse stuff sooner...

> an equivalent program on 0.5 also reports different values, but there I think it's biased towards just slightly overreporting the delta instead of massively underreporting it.

Naively I'd assume that this comes from hidpi shenanigans that were different in 0.5 (to be precise windows being bigger than actually reported, as coordinates were based on logical units back then), but I haven't checked yet to test this thesis.


Looking into this a bit I see two possible causes for the bug. The mouse delta values in ggez are based upon the value `ctx.mouse_context.last_delta`, which gets written to only at one place (somewhere in the event cycle).

The first problem could be that the values stem from [`winit_event::DeviceEvent::MouseMotion`](https://docs.rs/winit/0.24.0/winit/event/enum.DeviceEvent.html#variant.MouseMotion), which returns
> raw, unfiltered physical motion.

adding that it's a

> change in position in unspecified units.
> Different devices may use different units.

So these values may actually not be pixels, or at least they might be some weird form of them.

The other thing that I noticed is that `delta == (dx, dy)` returns true most of the time when I move the mouse very slowly (pixel by pixel). The difference gets worse the faster I move the mouse.
The reason for this could be that we don't actually accumulate all physical mouse changes, in case that there's more than one being handled during the current event loop. Instead, we only overwrite `last_delta`, so it's make sense for the value to be too small if many events override this value without adding their changes up.

The latter thing should be easy enough to check/fix, I'll try soon.

**Comment by PSteinhaus** [comment] 2021-08-24 09:21
Ok, so changing the event loop a little to calculate `last_delta` cumulatively using the `winit_event::DeviceEvent::MouseMotion`s doesn't seem to help. There are times when there's more than one of these events per frame, but the underlying problem seems to be a different one.

Now I'm relatively sure that the problem arises from the fact that these events return

> raw, unfiltered physical motion

which might mean they're triggered quicker/earlier than `winit_event::WindowEvent::CursorMoved`s. Since the cursor continues to move (as it's controlled by the OS) between the moments where these events are triggered it would make sense that they report diferent values.

winit having changed/grown between ggez 0.5 and 0.6 could then be another reason for why the results differ between these versions.

## A different solution

Anyway, I guess the solution to this is to just ignore `winit_event::DeviceEvent::MouseMotion`s, as these are also fired when the mouse is not even inside the game window, plus their values being inconsistent to [what we actually want to return](https://docs.rs/ggez/0.6.0/ggez/input/mouse/fn.delta.html), namely:

> the distance the cursor was moved during last frame, in pixels.

So instead we should probably calculate these values similiarly to what you do.
But, there's a catch:

There can be multiple `mouse_motion_event`s per frame (though most of the time there aren't).
This means, if we want to fix `mouse::delta` we still need to change things to calculate it cumulatively, but not using `DeviceEvent::MouseMotion`. Instead we must calculate / update it in the same place as the mouse position (when `WindowEvent::CursorMoved`s happen).

IF we'd do that (just checked) we'd get the expected behavior that is promised on `mouse::delta` (i.e. the x- and y-distance moved during the last frame).
BUT this would mean that your comparisons would still return `false` sometimes, whenever there are multiple `mouse_motion_event`s per frame.

## The actual solution (hopefully)

Therefore I propose changing the documentation of `mouse::delta` to something like

> The distance the cursor was moved between the latest two `mouse_motion_event`s

since I think this is what most people actually expect when they get `dx` and `dy` values (including myself). Sticking to the old expected behavior would mean that you (and others like you) would have to build in counter measures, to calculate the _correct_ values for `dx` and `dy` yourselves and that's probably not what we want...

Whether we decide to go for that or not, we definetely need to move the code updating the mouse delta into the case for `WindowEvent::CursorMoved` events.

**Comment by Nemo157** [comment] 2021-08-24 11:02
Another consideration is what the behaviour is like with `cursor_grabbed` and the cursor pressing against the window boundary, my initial guess was that would result in `x, y` remaining the same but continuing to get `dx, dy` values to use with relative motion, but instead it appears that `mouse_motion_event` stops firing. Calling `mouse::delta` continues to give delta values corresponding with the force pushed against the boundary, but when stationary it seems to keep the last delta value and never settles back to `0, 0`.

**Comment by PSteinhaus** [comment] 2021-08-24 15:18
> Another consideration is what the behaviour is like with `cursor_grabbed` and the cursor pressing against the window boundary, my initial guess was that would result in `x, y` remaining the same but continuing to get `dx, dy` values to use with relative motion, but instead it appears that `mouse_motion_event` stops firing.

I observe the same behavior and it makes sense that we do, as the `mouse_motion_event` is internally caused by a `WindowEvent::CursorMoved` event. If the cursor, as observed by the window, doesn't actually move I think it makes sense to not have any `mouse_motion_event`s. We could change things, so that these events are also fired when the mouse is pressed against the window boundary, but not actually moving, but that might be debateable, as the cursor really doesn't move at all. Then again the event is called `mouse_motion_event` not `cursor_motion_event`, so meh.


>  Calling `mouse::delta` continues to give delta values corresponding with the force pushed against the boundary, but when stationary it seems to keep the last delta value and never settles back to `0, 0`.

This also makes sense, when looking at the current implementation, though it's surely not exactly what we want.
The value that `mouse::delta` returns is actually currently set by a different event than the `WindowEvent::CursorMoved` event which causes the `mouse_motion_event`. Instead it is overwritten whenever a `DeviceEvent::MouseMotion` event fires, which also continues to happen whenever the mouse is physically moved (even when the cursor doesn't move, or it's outside the window, or the window is even out of focus!). Therefore it also never settles back down to `0, 0`, as it's only ever overwritten when there actually IS a movement of sorts.

## Proposal

Looking at all of this my current preference would be to do the following:
1. Use `mouse_context.last_delta` to store `dx`, `dy` values, generated whenever a `WindowEvent::CursorMoved{ logical_position, ... }` event fires, calculated as follows:
```rust
let current_pos = crate::input::mouse::position(ctx);
let diff = crate::graphics::Point2::new(logical_position.x as f32 - current_pos.x, logical_position.y as f32 - current_pos.y);

ctx
    .mouse_context
    .set_last_delta(crate::graphics::Point2::new(current_delta.x + diff.x as f32, current_delta.y + diff.y as f32));
```
This would mean that `mouse_context.last_delta` holds "The distance the cursor was moved between the latest two mouse_motion_events". Therefore:

2. We could (still) use `mouse_context.last_delta` to return the `dx`, `dy` values to be returned by `mouse_motion_event`s, but instead of calling `mouse::delta`, as we currently do, we call something like `mouse::latest_delta`, returning `mouse_context.last_delta`, and which can be private to the crate IMO. Whether to make it public or private might be a matter of taste though. I, for one, would keep it private to avoid confusion and inflating the API, since the value returned really only makes sense where it's actually returned automatically, which is inside a `mouse_motion_event`.

3. We'd need to introduce another field (something like `frame_delta`) on `MouseContext` for holding the value to be returned by `mouse::delta`, as well as a (crate private) setter function. I think it makes sense to keep the documentation (and therefore expected behavior) of this function (almost) the same, meaning that it should return "the distance the cursor was moved during the **current** frame, in pixels".

4. For it to actually deliver this behavior we'd need to change how it's calculated though. Instead of taking the value from `DeviceEvent::MouseMotion` events, as we currently do, we should calculate it together in one place with `last_delta`. But instead of being overwritten directly like `last_delta` it should be calculated cumulatively, so that it actually reflects the total change in the latest frame (the one currently running), even when more than one `mouse_motion_event` has fired this frame.
    
    4.1 This of course also means we'd need to set `frame_delta` back to zero somewhere. I guess this should be at the very end of the current frame, after `update` and `draw` have happened.

**Comment by PSteinhaus** [comment] 2021-08-31 07:06
I'm closing this now, as I'm content with how it's fixed.

Yet, if someone feels like debating the following feel free to reopen it:
> If the cursor, as observed by the window, doesn't actually move I think it makes sense to not have any mouse_motion_events. We could change things, so that these events are also fired when the mouse is pressed against the window boundary, but not actually moving, but that might be debateable, as the cursor really doesn't move at all. Then again the event is called mouse_motion_event not cursor_motion_event, so meh.

**Closed by PSteinhaus** 2021-08-31 07:06 UTC
Labels: bug
