### ISSUE TITLE
[Question] FPS limit

### ISSUE THREAD

**Issue by NChechulin** [ggez/ggez#899] opened 2021-02-16 16:04 UTC
Recently I noticed that my game has 60 fps. This number doesn't depend on debug/release build, so I assume that the fps is somehow limited by `ggez`.
I have a few questions:
- Am I correct?
- Is there any way to override the limit?
- If a user has, for example, a 144 Hz screen, will the limit still be 60 FPS or it will rise to 144?

**Comment by wait-what** [comment] 2021-02-21 11:48
I believe this is caused by vsync, so it does depend on the monitor's refresh rate.
As for overriding it, I tried to disable vsync, but the framerate is still capped at 60 fps for me, no matter what.
```rs
let cb = ggez::ContextBuilder::new("test", "test")
    .window_setup(
        ggez::conf::WindowSetup {
            title: "test".to_owned(),
            samples: ggez::conf::NumSamples::Zero,
            vsync: false,
            icon: "".to_owned(),
            srgb: true,
        }
    );
```

**Comment by PSteinhaus** [comment] 2021-02-23 13:32
Also, if you want to set the FPS yourself you can do so by calling [ggez::timer::check_update_time](https://docs.rs/ggez/0.5.1/ggez/timer/fn.check_update_time.html) inside your main loop. I personally use this to unify game logic cycles, but if you write your own main loop (meaning you call ```update``` and ```draw``` yourself instead of them being called automatically), I believe you can also change the draw frequency this way.

**Comment by IGBC** [comment] 2021-06-03 16:20
No reply from OP in 3 months. I assume he was happy with the answer, closing for now. If OP has more questions please open a new issue.

**Closed by IGBC** 2021-06-03 16:20 UTC
Labels: question
