### ISSUE TITLE
Artifacts When Rendering Text

### ISSUE THREAD

**Issue by CaptainKraft** [ggez/ggez#302] opened 2018-03-12 14:54 UTC
I'm drawing some large text on my game's main menu screen. Here is the basic gist of how I draw it:
```rust
let font = graphics::Font::new(ctx, "/DejaVuSansMono.ttf", 128)?,
let text = graphics::Text::new(ctx, "A Viking Gone Rogue", &font)?;
let dest = graphics::Point2::new(
    800.0 / 2.0 - text.width() as f32 / 2.0,
    600.0 / 2.0 - text.height() as f32 * 3.0,
);
graphics::set_color(ctx, graphics::Color::new(1.0, 0.1, 0.1, 1.0))?;
graphics::draw(ctx, &text, dest, 0.0)?;
graphics::set_color(ctx, graphics::Color::new(1.0, 1.0, 1.0, 1.0))?;
```

And here is the result:

![artifacts-play](https://user-images.githubusercontent.com/1237356/37290606-505f4b0a-25d2-11e8-86cb-d749c1cf5c94.png)
Artifacts look like horizontal tearing across each letter (except the L). This text uses DejaVuSansMono.ttf at size 128.

![artifacts-title](https://user-images.githubusercontent.com/1237356/37290613-541451dc-25d2-11e8-9ab7-1083938814e0.png)
Artifact on far bottom-left corner. This text uses a bold font called Mont at size 50.

It's possible that this could be caused by my own system. I'm on 64bit Arch Linux with proprietary NVidia drivers.

**Comment by icefoxen** [comment] 2018-03-12 18:05
Can't reproduce.  :-(  64 bit Debian with open source AMDGPU drivers.

![image](https://user-images.githubusercontent.com/1335133/37301083-0202fe3a-25fe-11e8-97a1-cad664d55504.png)

Suggestions: Tinker with number of samples and see if that makes any difference?  Try with the nouveau drivers?

**Comment by icefoxen** [comment] 2018-03-13 17:55
Actually, I have a computer with a NVidia GPU, let me try that... might have to install Arch on it though.

**Comment by icefoxen** [comment] 2018-03-22 21:02
Also if you are rotating the text at all there artifacts might be apparent, a la https://github.com/alexheretic/gfx-glyph/issues/20#issuecomment-374909336

Still a weird issue.  But it appears that rusttype has woken up and made a couple new releases this spring, so huzzah.  Updating it and seeing if there's any difference may be interesting.

I still suspect the graphics card and don't have any great ideas for how to investigate this, but it's an idea.

**Comment by icefoxen** [comment] 2018-03-29 00:09
@CaptainKraft Rusttype has been updated to the most recent, see if you still have this artifact?

**Comment by CaptainKraft** [comment] 2018-03-29 20:46
Still broken. It's probably something to do with my GPU drivers or something else on my end. Not sure.

**Comment by icefoxen** [comment] 2018-07-06 15:35
Upstreamed to rusttype for helo: https://gitlab.redox-os.org/redox-os/rusttype/issues/121

**Comment by icefoxen** [comment] 2018-10-23 17:34
Closed and hopefully resolved by upstream.

**Closed** 2019-07-15 17:21 UTC
Labels: Type-CODE, bug
