### ISSUE TITLE
set_screen_coordinates() is broke as heck

### ISSUE THREAD

**Issue by sector-f** [ggez/ggez#134] opened 2017-08-29 22:23 UTC
I'm currently using a tiling window manager (bspwm), which may or may not be relevant. I haven't tested on other WMs.

When creating the window, I specify 800x600 as the window's size. The window manager ignores this and tiles the window, which then has a black space on top, because I can apparently only draw 800 pixels high.

From here, I put the window into floating mode, and it gets resized to 800x600. It renders correctly.

Then I go into fullscreen mode. The only part of the window containing an image is an 800x600 rectangle in the lower-left corner.

Note that all methods I've found to report the window size—`get_size()`, `get_drawable_size()`, and `resize_event()`—return the actual window size.

**Comment by icefoxen** [comment] 2017-08-29 22:36
The listed methods all *correctly* return the actual window size?  That's not what I recall you saying on IRC but I may be misremembering.

I assume the problem is that the viewport that gets drawn on doesn't resize with the screen itself?  Does it work correctly when you reset the bounds with <https://docs.rs/ggez/0.3.3/ggez/graphics/fn.set_screen_coordinates.html> ?

**Comment by sector-f** [comment] 2017-08-29 22:59
I added this code:

````rust
fn resize_event(&mut self, ctx: &mut Context, width: u32, height: u32) {
    let _ = graphics::set_screen_coordinates(ctx, 0.0, width as f32, 0.0, height as f32);
}
````

The size of the rendered area is still the same, but it appears to have affected...something. Before, in fullscreen, the rendered image was correct for the size of the window, just missing part of the image. With this code added, the rendered image is correct for the visible area.

I took a screencapture to show the difference: https://u.teknik.io/eNiuV.webm

**Comment by icefoxen** [comment] 2017-09-04 18:04
Does it work when you scale and reposition the rect to fill the screen?

**Comment by icefoxen** [comment] 2017-09-30 18:34
Okay, as noted in https://github.com/ggez/ggez/issues/162#issuecomment-333327140 , something seems to be... subtly broken in `set_screen_coordinates()`.  I'm not quite sure what but shall find out.  Once I do, the `graphics_settings` example will be updated to contain a canonical example of how to do this.

**Comment by osa1** [comment] 2017-10-28 11:20
Possibly related: #197

**Comment by icefoxen** [comment] 2017-11-08 15:58
Also related: #179

**Comment by svenstaro** [comment] 2017-11-16 16:41
> I think for consistency with Love2D and eventual ease-of-use with Vulkan, we should just go with 0,0 in the upper-left corner, Y increasing down. If people want to change that, we now have functions to let them set projections and transforms pretty arbitrarily, so they should have an easy time with it, and ggez doesn't have to try to do anything fancy under the hood.

I absolutely agree with this. It's intuitive for people coming from other frameworks.

**Comment by icefoxen** [comment] 2017-12-12 19:28
This should be done now.  Everyone please test!

**Comment by icefoxen** [comment] 2017-12-16 20:58
Should be fixed.

**Comment by icefoxen** [comment] 2017-12-16 21:02
heeeeeck not fixed yet crud

something changed with how we scale drawable's when the screen projection changes

gdi

**Comment by icefoxen** [comment] 2017-12-17 16:33
ARGH it was broken in commit cbef97d5707ff2b2d1b2a764759f4db1bf17820f

Now WHAT HAPPENED.

**Closed** 2017-12-17 16:37 UTC
Labels: bug, [CODE]
