### ISSUE TITLE
Tiles rendering 20 fps

### ISSUE THREAD

**Issue by FloVanGH** [ggez/ggez#131] opened 2017-08-24 13:48 UTC
I'm implemented a tile rendering function and build an example that draws 1500 tiles. The application runs only with 20 fps. Here you can find my code https://github.com/FloVanGH/pg-engine/blob/master/src/drawing.rs. I hope you can help me to improve the fps :-). 

I tried the 0.3.3 and the current master build of ggez: same result.

**Comment by icefoxen** [comment] 2017-08-25 00:26
Duplicate of #127 

I'll take a look when I have a moment.

**Comment by FloVanGH** [comment] 2017-08-25 05:39
Ok thank you.

**Comment by FloVanGH** [comment] 2017-08-25 13:48
Tested release build and now it runs with 60+ fps. Hope Spritebatch will increase the debug fps ;-) . Thank you for your commitment.

**Closed** 2017-08-25 14:15 UTC
Labels: duplicate

**Comment by icefoxen** [comment] 2017-08-26 17:31
Debug FPS is actually problematic because it gets *very* CPU-limited very quickly.  In release mode the compiler does a *lot* more optimization and things in general run much faster; that's not something ggez can do much about.

In my game project I compile with `opt-level=1` even in debug mode, which is a half-decent compromise.

**Comment by FloVanGH** [comment] 2017-08-27 06:14
I known but I had no idea that optimization is so extensive, that it has such great influence on the fps. In other languages I haven't notice it so much. 

The `opt-level=1` build runs now with 55-60 fps, that's enough for debugging ;-). Thank you very much for this hint.

But should the SpriteBatch struct also improve the drawing performance?

Your project is great, it's exactly what I was looking for :-).

**Comment by icefoxen** [comment] 2017-08-27 16:59
Yeah, partially because you can't currently set optimization level for libraries separately from your program, so when you build in debug mode then *everything* builds in debug mode, even the stuff you have no interest in debugging.  `gfx-rs` is full of array bounds checks and structure translations that get sped up a *lot* by optimizations.

Glad you like it!  Always nice to have people doing cool stuff with it.

**Comment by FloVanGH** [comment] 2017-08-28 15:27
Ah ok that explains it. 

:-)
