### ISSUE TITLE
Offset + Text in 0.5

### ISSUE THREAD

**Issue by eqv** [ggez/ggez#562] opened 2019-01-20 22:35 UTC
It seems that setting offset on the draw params of a simple Text object does not affect the rendering at all.

**Comment by icefoxen** [comment] 2019-01-24 04:09
Now that's interesting and not good.  We should check to see if SpriteBatch has the same problem.

**Comment by rshadown** [comment] 2020-02-12 10:31
I am running into the same problem. Offset does nothing, while replacing it with .dest does change the position of the text.

**Comment by alexschrod** [comment] 2020-04-26 08:48
@icefoxen I don't know about `SpriteBatch` (haven't used it yet), but I can tell you that `Mesh` also doesn't respect offsets. Here's my draw code:
```rust
let draw_param_title = graphics::DrawParam::new()
    .dest([screen_coordinates.w / 2., screen_coordinates.h / 2.])
    .offset([0.5, 0.5]);

graphics::draw(ctx, &self.title, draw_param_title)?;

let mesh = create_outline_mesh(ctx, self.title.dimensions())?;
graphics::draw(ctx, &mesh, draw_param_title)?;
```
Here's `create_outline_mesh`:
```rust
fn create_outline_mesh(
    ctx: &mut Context,
    dimensions: graphics::Rect,
) -> GameResult<graphics::Mesh> {
    let mut mb = graphics::MeshBuilder::new();
    mb.rectangle(
        graphics::DrawMode::Stroke(graphics::StrokeOptions::DEFAULT),
        dimensions,
        graphics::WHITE,
    );
    mb.build(ctx)
}
```
and here's what gets drawn:
![image](https://user-images.githubusercontent.com/767490/80302567-04ecb300-87ab-11ea-93b5-d511e032007f.png)
If I manually do the offset calculation for the mesh draw command:
```rust
graphics::draw(
    ctx,
    &mesh,
    draw_param_title.clone().dest([
        draw_param_title.dest.x - f32::from(self.title.width()) / 2.,
        draw_param_title.dest.y - f32::from(self.title.height()) / 2.,
    ]),
)?;
```
I get what I expect:
![image](https://user-images.githubusercontent.com/767490/80302603-43826d80-87ab-11ea-81e9-da8381f6f916.png)

**Comment by gliderkite** [comment] 2020-05-03 13:55
I noticed the same behaviour as well when trying to simply set the `DrawParam::offset` to a `Mesh`, i.e. no effect on the rendering, the position of my `Mesh` did not change. I am using version `0.5`, and I noticed that the implementation of `DrawParam:: to_na_matrix` was [changed](https://github.com/ggez/ggez/commit/5ae816eb82d534f1fdbdae3ac86d15a62c13fa2d#diff-702ae68368fafa655c100c7d6266bc32), unfortunately the same bug seems to exists also with the new implementation.

Having a look at the implementation of `DrawParam::to_na_matrix` [from the docs](https://docs.rs/ggez/0.5.1/src/ggez/graphics/drawparam.rs.html#112-121) I noticed something strange (I'm not an expert in this field so please bare with me):

```rust
let translate = Matrix4::new_translation(&Vec3::new(self.dest.x, self.dest.y, 0.0));
let offset = Matrix4::new_translation(&Vec3::new(self.offset.x, self.offset.y, 0.0));
let offset_inverse =  Matrix4::new_translation(&Vec3::new(-self.offset.x, -self.offset.y, 0.0));
let axis_angle = Vec3::z() * self.rotation;
let rotation = Matrix4::new_rotation(axis_angle);
let scale = Matrix4::new_nonuniform_scaling(&Vec3::new(self.scale.x, self.scale.y, 1.0));
translate * offset * rotation * scale * offset_inverse
```

What is the point of `offset_inverse`? It looks like it's the factor that will actually nullify the original offset (and probably the new implementation tries to replicate the same logic). If I remove the `offset_inverse` from the equation (and simply return `translate * offset * rotation * scale`) I can see the offset of my circle changing, and being drawn in the expected location, when I set it with:

```rust
let point = na::Point2::new(0.0, 0.0);
let radius = 30.0;
let tolerance = 3.0;
let circle = graphics::Mesh::new_circle(
    ctx,
    graphics::DrawMode::fill(),
    point,
    radius,
    tolerance,
    graphics::WHITE,
)?;

let dest = na::Point2::new(radius, radius);
let param = graphics::DrawParam::default()
    .dest(dest)
    .offset(na::Point2::new(100.0, 100.0));
graphics::draw(ctx, &circle, param)?;
```

The problem IMO arises from the confusion of the meaning of this `offset`, especially when related with the `dest`, and I couldn't find the distinction documented in the [docs](https://docs.rs/ggez/0.5.1/ggez/graphics/struct.DrawParam.html). Was there supposed to be a difference, and if so what should it be and would it be possible to document it in the `DrawParam` module (when the bug is fixed)? If there is no difference between the two maybe we should consider deprecating `dest`. Thanks.

**Comment by icefoxen** [comment] 2020-05-05 14:04
`offset` means the point at which a rotation will rotate around.  When I was figuring out the math for this, the simplest way recommended to me was to translate the object so the offset is at 0,0, rotate it, and then translate it back.  That's what `offset_inverse` and `offset` do, respectively.

One source of confusion with this is that while an `Image` always assumes that the top-left corner is 0,0, a `Mesh` can have 0,0 pretty much anywhere, depending on how it was built.  Often it's at the center, not at the top-left corner.

**Comment by gliderkite** [comment] 2020-05-05 20:21
Thanks for the clarification and for your work with `ggez`.

If that is the case, I've seen graphics libraries exposing rotation APIs where you would specify both angle and center point of the rotation (for example [Direct2D](https://docs.microsoft.com/en-gb/windows/win32/api/d2d1helper/nf-d2d1helper-matrix3x2f-rotation)). In this case the API would be something like `DrawParam::rotation(angle: f32, center: Point2)`, which would make `dest` redundant and replaceable by `offset` (a more descriptive name IMO), solving the confusion issue that was probably the source of this problem (and if you didn't have to publicly expose the `DrawParam` fields you would be able to store all, or just the single, transformation besides the Color).

**Comment by icefoxen** [comment] 2020-05-06 17:30
Hmm, not a terrible idea actually. That's basically what happens internally anyway but forcing you to always specify the two together might make it more clear.

**Comment by tatref** [comment] 2020-05-20 21:33
I have a similar issue.

When trying to rotate a `Rectangle` (so a `Mesh`) and an `Image` at their center, I noticed that the offset for `Image` must be `[0.5, 0.5]`, but the offset for `Rectangle` must be `[rectangle.w, rectangle.h]`

Is this expected behavior?

**Comment by PSteinhaus** [comment] 2021-11-08 22:35
> I have a similar issue.
> 
> When trying to rotate a `Rectangle` (so a `Mesh`) and an `Image` at their center, I noticed that the offset for `Image` must be `[0.5, 0.5]`, but the offset for `Rectangle` must be `[rectangle.w, rectangle.h]`
> 
> Is this expected behavior?

In this comment (and the others before it) lies a crucial hint towards the solution of this problem, which is that `offset` is apparently applied _after_ scaling, which is definitely not desired.
Luckily, I'm pretty sure the solution has already been applied and that it was [this](https://github.com/ggez/ggez/commit/d7b4df058dde8dbd317d5ef48d8a1b15fefb17da).
Had I found and read this earlier it might have helped me save a little bit of time, but I'm not sure. I don't remember the process very clearly.

>
> `offset` means the point at which a rotation will rotate around. When I was figuring out the math for this, the simplest way recommended to me was to translate the object so the offset is at 0,0, rotate it, and then translate it back. That's what `offset_inverse` and `offset` do, respectively.

Now i finally get to see how this error was made and what the intention behind this was. I always wondered why the matrix was supposed to be calculated this way. Understanding it now is very satisfying.

Now I get why you'd have wanted to put two offset matrices in the formula for the transformation matrix. But since offsets do not only get used to rotate things, but also to center them on the destination for example, I now feel confident that taking out the one that didn't make sense to me was actually the right thing to do.

Sadly I just re-tested the behavior of offsets on Text, and the problem remains.
The reason for this is that, starting with ggez 0.7.0, I changed offset behavior on SpriteBatch and MeshBatch so that offets are now interpreted as absolute offsets, instead of relative ones (like for `Image`).

Generally, this makes sense for batches, as I tried to lay out in [a related issue](https://github.com/ggez/ggez/issues/736#issuecomment-955791069). But it doesn't fit `Text`.

Now I see two ways to fix this: The easy and the (probably more) correct way.

- easy: Internally, apply a workaround, like the ones I used on `SpriteBatch` and `MeshBatch` to rescale the offset to fit to the dimensions of the `Drawable`. The downsides of the relative offset interpretation don't apply to `Text`, as far as I can see, so this should be fine, and through the use of the cached metrics, possibly even somewhat efficient, or at least efficient enough.
- (more) correct: Instead of only giving the user the opportunity to set the destination of the text, also give them the opportunity to apply all the other transformations, that is, allow them to supply a `DrawParam` per queued `Text`. To achieve this a more thorough look into the inner workings of `draw_queued_text` is necessary. If we're lucky this could be solved by just crunching down both the param given by the user and the param returned by glyphbrush to tell the SpriteBatch where to take the glyph from and where to render it to, into matrices, which could then be multiplied to get the final transformation. But something in the back of my head says that it won't be all that easy; it might be wrong though, we'll see.

Normally, as we're about to move to a new graphics backend anyway, I'd go with the easy way for such things for now.
But since I can imagine that drawing text will work very similiarly with the coming backend too, I think it might be worth to go and try the correct approach.

**Comment by PSteinhaus** [comment] 2022-05-10 09:06
Ok, with #1020 merged things have changed.
jazzfool was so nice to not only improve text performance by using an additional glyph-wise shader, but to also allow `Text` to be drawn using all the features of `DrawParam` (except `src`, which doesn't do anything as textures text isn't currently a thing in ggez). And not only that, as a final touch, he also [changed offset behavior on `Text` to be relative](https://github.com/ggez/ggez/pull/1020/commits/dd322f3ea346d8d7f1f7c44e2b2b7ed03978934e). What a joy.
With this the more correct solution has been implemented.

**Closed by PSteinhaus** 2022-05-10 09:06 UTC
Labels: bug, Type-CODE
