### ISSUE TITLE
Keyboard state API

### ISSUE THREAD

**Issue by NoraCodes** [ggez/ggez#404] opened 2018-06-14 21:16 UTC
It would be really useful to have a keyboard state API, similar to the mouse and gamepad state API. This would make writing keyboard-driven games significantly easier.

**Comment by icefoxen** [comment] 2018-06-14 22:09
There is a rather basic crate for this in the `input` module for https://github.com/ggez/ggez-goodies/ .  Would be nice to have input API's be more consistent for all device types though, you are correct.

**Comment by Ratysz** [comment] 2018-06-15 21:12
Should be covered by #406. @LeoTindall, can you take a look, does that work for your usecase?

Sort-of-relevant, I'm *really* itching to go on a big consistency-improving rampage. Module APIs, docs, tests, doctests... I suppose I'm content with doing it piece-by-piece with modules I touch by PRs.

**Comment by icefoxen** [comment] 2018-06-16 05:58
@Ratysz We definitely need it, yes. I've been working on it, just not terribly quickly. Ping on Discord this weekend or when you have free time and we can coordinate.

**Comment by icefoxen** [comment] 2018-07-04 19:06
Should be pretty well cleaned up as of commit 7acb91b.  Just need to make sure that modifier keys get handled correctly.

**Comment by icefoxen** [comment] 2018-07-05 19:51
Works in 522355d05a049dbf893b21f2837775412d199196 , though the handling of keyboard events is a little... squirrelly.

We have the `ScanCode`, which is the position of the key on the keyboard.  Then we have `VirtualKeyCode`, which is the (lowercase) letter printed on the key (basically).  Right now we do all event handling on `VirtualKeyCode`.  This means that if someone presses `/` we get a key down event because that button has a `VirtualKeyCode`, but if someone presses `shift-/` we don't get a key down event.

I THINK we want to be using scancodes always, and provide the `VirtualKeyCode` when available.  It's not a difficult change, though.  Just have to untangle everything a bit.  Modifier handling is similarly more sticky than I think it should be...  That's partially `winit`'s fault.

**Comment by icefoxen** [comment] 2018-07-10 01:19
In SDL we used `KeyCode`, not `ScanCode`, so not sending us `KeyCode`'s on all these events might be a winit bug.  There's a few open issues about such things, dig through them.

**Comment by icefoxen** [comment] 2018-07-13 15:45
Nope, using `KeyCode` is correct, KeyCode vs. ScanCode has the same meaning in SDL2 as in winit 

Okay, upon investigation, when you press, `/` then SDL sends you a `Slash` keycode.  Winit does the same.  But if you press `shift-/`(aka `?`), SDL sends you `Slash` keycode and Winit does not.  Not sure what the "correct" approach is.

**Comment by icefoxen** [comment] 2018-07-13 17:13
Okay, confirmed it's a bug in winit; need to submit a PR for it before closing this.

**Comment by beatgammit** [comment] 2018-08-01 02:25
@icefoxen Are you working on this? If not, I'm down for taking a look.

**Comment by icefoxen** [comment] 2018-08-01 13:13
I dug into it some but got lost in a twisty maze of X11 documentation, all alike.  Feel free if you want.

**Comment by icefoxen** [comment] 2019-07-03 20:03
The state API now works but the winit bug is still broken, declaring that "not my problem for now".  This issue is still open but no longer blocking release.

**Closed** 2019-07-20 18:06 UTC
Labels: Type-CODE, bug, dependency bug, enhancement
