### ISSUE TITLE
Resized window not rendering correctly

### ISSUE THREAD

**Issue by PvdBerg1998** [ggez/ggez#202] opened 2017-11-08 18:56 UTC
See https://gist.github.com/PvdBerg1998/221f95b18fbd0d94e4779bee216eff77 .

As described on IRC, "the screen started at w=720. im rendering a rect of w=720 : the whole screen is filled. then I resize it to say w=1000 and render a rect of w=1000, but the new 280 pixels stay clear."

**Comment by PvdBerg1998** [comment] 2017-11-08 19:06
This is definitely a bug. I have been playing around with it and it seems to only bug out in certain directions, sometimes.

**Comment by PvdBerg1998** [comment] 2017-11-08 19:18
![image](https://user-images.githubusercontent.com/27141525/32569280-f916b3e6-c4c0-11e7-88d9-1c7edf74ba31.png)
Window: (300, 300). Rendered: (0, 0, 300, 300)

![image](https://user-images.githubusercontent.com/27141525/32569355-2df91982-c4c1-11e7-8a23-4d3ced93162d.png)
Window: (808, 300). Rendered: (254, 0, 300, 300). End x of the rectangle: 254 + 300 = 554, which is 68% of the width of the window. But as seen in the image, it is not rendering that far.

![image](https://user-images.githubusercontent.com/27141525/32569525-a1ae1dd2-c4c1-11e7-9ddf-1db99c680c0b.png)
Window: (300, 490). Rendered: (0, 95, 300, 300). Start y = 95 = 20% of the height. The rectangle definitely does not start at 19% of the height. End y = 95 + 300 = 395 = 80% of the height. The rectangle ends at 100% : it is 20% too far down.

**Comment by sector-f** [comment] 2017-11-10 20:51
Possible duplicate of/related to #134

**Comment by icefoxen** [comment] 2017-12-12 23:33
@PvdBerg1998 , this should be fixed in master now. Please confirm; it may not be perfect and more use cases are good. See the `graphics_settings` example.

**Closed** 2017-12-17 16:39 UTC
Labels: bug, [CODE]
