### ISSUE TITLE
canvas not drawing all draw calls

### ISSUE THREAD

**Issue by Dumdidldum** [ggez/ggez#1140] opened 2022-11-22 22:37 UTC
**Describe the bug**
Calling draw many times to a canvas which is not the screen canvas "forgets"/ignores one draw call
This does not happen when you draw everything directly to the "Canvas::from_frame"

**To Reproduce**
call draw many times on one canvas, one draw call will not be executed

**Expected behavior**
all draw calls should be executed

**Screenshots or pasted code**
drawing 100 * 100 squares with side length 5 onto a canvas causes one of them to not be drawn
![image](https://user-images.githubusercontent.com/40397971/203434707-a6a9c5b1-8e60-4256-b315-2f0f9169b6dc.png)
Yellow = drawn squares
Black = background of inner canvas
Pink = background of screen canvas

in the yellow square you can see the one square not drawn as a black square

Code used: (stolen from the super simple example)
```rust
use ggez::{
    event,
    glam::*,
    graphics::{self, Canvas, Color, DrawParam, Image, Rect},
    Context, GameResult,
};

struct MainState {
    circle: graphics::Mesh,
    image: Image,
}

impl MainState {
    fn new(ctx: &mut Context) -> GameResult<MainState> {
        let circle = graphics::Mesh::new_rectangle(
            ctx,
            graphics::DrawMode::fill(),
            Rect::new(0., 0., 5., 5.),
            Color::YELLOW,
        )?;

        let image = Image::new_canvas_image(ctx, ctx.gfx.surface_format(), 700, 700, 1);

        Ok(MainState { circle, image })
    }
}

impl event::EventHandler<ggez::GameError> for MainState {
    fn update(&mut self, _ctx: &mut Context) -> GameResult {
        Ok(())
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult {
        let mut screen_canvas = graphics::Canvas::from_frame(ctx, Color::MAGENTA);

        let mut inner_canvas = Canvas::from_image(ctx, self.image.clone(), Some(Color::BLACK));

        for y in 0..100 {
            for x in 0..100 {
                inner_canvas.draw(&self.circle, Vec2::new((x * 5) as f32, (y * 5) as f32));
            }
        }
        inner_canvas.finish(ctx).unwrap();

        screen_canvas.draw(&self.image, DrawParam::default());

        screen_canvas.finish(ctx)?;

        Ok(())
    }
}

pub fn main() -> GameResult {
    let cb = ggez::ContextBuilder::new("super_simple", "ggez");
    let (mut ctx, event_loop) = cb.build()?;
    let state = MainState::new(&mut ctx)?;
    event::run(ctx, event_loop, state)
}
```

**Hardware and Software:**
 - ggez version: current 0.8.1
 - OS: recent Archlinux
 - Graphics card: Nvidia RTX 3070
 - Graphics card drivers: nvidia proprietary driver, version 520.56.06, from nvidia-all

**Comment by jazzfool** [comment] 2022-11-23 12:16
Occurs on 0.8.1 thru to devel, but does not occur with #1139, so this is likely another case of #1129
Could you confirm running it off that branch indeed fixes it? (`ggez = { git = "https://github.com/jazzfool/ggez", branch = "devel" }`)

**Comment by Dumdidldum** [comment] 2022-11-23 18:40
can confirm, on your version the issue does not show up!

**Comment by nobbele** [comment] 2022-12-01 16:27
closing as a duplicate of #1129

**Closed by nobbele** 2022-12-01 16:27 UTC
