### ISSUE TITLE
Not working on OpenGL 2.1 GPU's

### ISSUE THREAD

**Issue by LaineZ** [ggez/ggez#795] opened 2020-07-12 09:08 UTC
**Describe the bug**
Game won't start if GPU supports 2.1 OpenGL maximum crashes with these message:

``Error: WindowCreationError(NoAvailablePixelFormat)``

**To Reproduce**
Run game on very-old SM 2.0 GPU with default window settings and change OpenGL version

```
Backend::OpenGL {
    major: 2,
    minor: 1,
}
```

If you turn off srgb in window setup you got another error 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Other', /home/fulstop/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-0.18.2/src/factory.rs:152:9
```

**Expected behavior**
Game starts normally

**Hardware and Software:**
 - ggez version: 0.5.1 (crates.io)
 - OS: Ubuntu 20.04
 - Graphics card: ATI RS482M (Xpress 200M)
 - Graphics card drivers: Mesa 20.2.0-devel (git-6d8e2ce 2020-07-06 focal-oibaf-ppa)

**Comment by LaineZ** [comment] 2020-07-12 16:04
This similar to #770

**Comment by icefoxen** [comment] 2020-08-09 15:45
Yeah, duplicate of #770 .

**Closed by icefoxen** 2020-08-09 15:45 UTC
