### ISSUE TITLE
Panic in Canvas::new() on windows

### ISSUE THREAD

**Issue by sullyj3** [ggez/ggez#720] opened 2019-12-18 12:50 UTC
**Describe the bug**
Panic in Canvas::new()

Backtrace:
```
PS C:\Users\James\Code\rust_platformer> $Env:RUST_BACKTRACE=1; cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.49s
     Running `target\debug\rust_platformer.exe`
thread 'main' panicked at 'Error InvalidValue creating texture: Info { kind: D2(240, 160, Multi(0)), levels: 1, format: R8_G8_B8_A8, bind: RENDER_TARGET | SHADER_RESOURCE | TRANSFER_SRC, usage: Data }, hint: Some(Srgb)', C:\Users\James\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx_device_gl-0.16.2\src\factory.rs:449:13
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.37\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:76
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:60
   3: core::fmt::write
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libcore\fmt\mod.rs:1030
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\io\mod.rs:1412
   5: std::sys_common::backtrace::_print
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:64
   6: std::sys_common::backtrace::print
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:196
   8: std::panicking::default_hook
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:210
   9: std::panicking::rust_panic_with_hook
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:473
  10: std::panicking::continue_panic_fmt
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:380
  11: std::panicking::begin_panic_fmt
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:335
  12: gfx_device_gl::factory::{{impl}}::create_texture_raw
             at C:\Users\James\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx_device_gl-0.16.2\src\factory.rs:449
  13: ggez::graphics::canvas::CanvasGeneric<ggez::graphics::GlBackendSpec>::new
             at C:\Users\James\.cargo\registry\src\github.com-1ecc6299db9ec823\ggez-0.5.1\src\graphics\canvas.rs:66
  14: rust_platformer::Platformer::new
             at .\src\main.rs:86
  15: rust_platformer::main
             at .\src\main.rs:485
  16: std::rt::lang_start::{{closure}}<()>
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\src\libstd\rt.rs:64
  17: std::rt::lang_start_internal::{{closure}}
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\rt.rs:49
  18: std::panicking::try::do_call<closure-0,i32>
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:292
  19: panic_unwind::__rust_maybe_catch_panic
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libpanic_unwind\lib.rs:80
  20: std::panicking::try
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:271
  21: std::panic::catch_unwind
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panic.rs:394
  22: std::rt::lang_start_internal
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\rt.rs:48
  23: std::rt::lang_start<()>
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\src\libstd\rt.rs:64
  24: main
  25: invoke_main
             at d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  26: __scrt_common_main_seh
             at d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  27: BaseThreadInitThunk
  28: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\rust_platformer.exe` (exit code: 101)
```

Links to relevant code:
https://docs.rs/ggez/0.5.1/src/ggez/graphics/canvas.rs.html#66
https://docs.rs/gfx_device_gl/0.16.2/src/gfx_device_gl/factory.rs.html#449

**To Reproduce**
```
impl Platformer {
    fn new(ctx: &mut Context) -> Platformer {
        // SNIP

        Platformer {
            // SNIP

            world_canvas: Canvas::new(ctx, 240, 160, ggez::conf::NumSamples::Zero)
                .expect("couldn't init world_canvas"),
            ui_canvas   : Canvas::new(ctx, 2206, 1504, ggez::conf::NumSamples::Zero)
                .expect("couldn't init ui_canvas"),
        }
    }
}
```
The panic is on the line starting with world_canvas (line 86, mentioned in the backtrace). I'm not sure what other info I should provide to reproduce, if any. These seem like relatively straightforward calls. Happy to provide the entire main.rs if necessary.

**Expected behavior**
No panic? I'm honestly not sure if I'm doing something wrong here, I'm new to game/graphics programming.

I'm attempting to create two separate layers to render a pixelly world and a hi res UI on top. 

**Hardware and Software:**
 - ggez version: 0.5.1
 - OS: Windows 10
 - Graphics card: Intel HD Graphics 620 (Surface Laptop i5 integrated)
 - Graphics card drivers: Stock

**Comment by icefoxen** [comment] 2019-12-18 20:42
Thanks for the bug report!  I'll see if I can reproduce.

**Comment by telastrus** [comment] 2020-01-08 01:06
I ran into a similar issue on Linux, and I found that changing the number of samples from Zero to One got it to work. I can also post logs if desired.

**Comment by sullyj3** [comment] 2020-01-10 15:42
Yup, that seems to fix things for me as well.

**Comment by PSteinhaus** [comment] 2021-06-01 13:28
Since NumSamples::Zero has been removed I guess this is no longer an issue, so I'll close it now.
It may be a bit late to comment on your original project, but if you're still working on it, or if someone thinking about doing something similiar reads this, then please consider to not use a second canvas for drawing the UI (except if the UI is pretty static and complex, then it could of course make sense), but to instead call ```set_screen_coordinates``` with the dimensions of your UI and then draw directly on the screen.

**Closed by PSteinhaus** 2021-06-01 13:28 UTC
Labels: bug
