### ISSUE TITLE
unable to run examples in archlinux

### ISSUE THREAD

**Issue by Jack-Ji** [ggez/ggez#698] opened 2019-10-27 09:28 UTC
**Describe the bug**
unable to run example/01_super_simple in ggez

**Screenshots or pasted code**
```
[jack@jfun ggez]$ RUST_BACKTRACE=full cargo run --example 01_super_simple
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/examples/01_super_simple`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0:     0x55c086d7248b - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x55c086d7248b - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x55c086d7248b - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x55c086d7248b - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x55c086d7248b - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x55c086d72166 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x55c086d72bfd - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x55c086d72782 - std::panicking::continue_panic_fmt::h25abfbb4e5b7043a
                               at src/libstd/panicking.rs:384
   8:     0x55c086d72666 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x55c086d8f3ed - core::panicking::panic_fmt::h7e9f94035af782b3
                               at src/libcore/panicking.rs:85
  10:     0x55c086d8f32c - core::panicking::panic::hda536e6f3accfb91
                               at src/libcore/panicking.rs:49
  11:     0x55c086962c6b - core::option::Option<T>::unwrap::ha665dc2eb07970eb
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/macros.rs:12
  12:     0x55c0869ad1d7 - winit::platform::platform::wayland::window::Window::get_current_monitor::h25dc713f0d40ff61
                               at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.4/src/platform/linux/wayland/window.rs:290
  13:     0x55c08650b03d - winit::platform::platform::Window::get_current_monitor::h6fa6497a50f76db6
                               at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.4/src/platform/linux/mod.rs:358
  14:     0x55c0864ce69e - winit::window::<impl winit::Window>::get_current_monitor::h4fa590320846ef23
                               at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.4/src/window.rs:412
  15:     0x55c0864055f8 - ggez::graphics::context::GraphicsContextGeneric<B>::set_window_mode::hda2c390449e50d28
                               at src/graphics/context.rs:537
  16:     0x55c086426555 - ggez::graphics::context::GraphicsContextGeneric<ggez::graphics::GlBackendSpec>::new::h2e6fee878c23238b
                               at src/graphics/context.rs:301
  17:     0x55c086416170 - ggez::context::Context::from_conf::hd9e604abb050f809
                               at src/context.rs:88
  18:     0x55c086417dda - ggez::context::ContextBuilder::build::h2a7a5e9a05807a4f
                               at src/context.rs:304
  19:     0x55c0863b2e5a - _01_super_simple::main::h5514129d03e79869
                               at examples/01_super_simple.rs:46
  20:     0x55c0863b0055 - std::rt::lang_start::{{closure}}::h1902319748adeb03
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  21:     0x55c086d72603 - std::rt::lang_start_internal::{{closure}}::h4e93c1949c7a1955
                               at src/libstd/rt.rs:49
  22:     0x55c086d72603 - std::panicking::try::do_call::h9440ccd4dc467eaa
                               at src/libstd/panicking.rs:296
  23:     0x55c086d7714a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  24:     0x55c086d7310d - std::panicking::try::hc046e7ee42ee744f
                               at src/libstd/panicking.rs:275
  25:     0x55c086d7310d - std::panic::catch_unwind::h27dfc457c200aee0
                               at src/libstd/panic.rs:394
  26:     0x55c086d7310d - std::rt::lang_start_internal::hea1b49a567afe309
                               at src/libstd/rt.rs:48
  27:     0x55c0863b0029 - std::rt::lang_start::h7954301adc2a7199
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  28:     0x55c0863b326a - main
  29:     0x7fcb0d451153 - __libc_start_main
  30:     0x55c0863a81ae - _start
  31:                0x0 - <unknown>
```

**Hardware and Software:**
 - ggez version: current git master.
 - OS: archlinux
```
[jack@jfun ggez]$ lspci
00:00.0 Host bridge: Intel Corporation 2nd Generation Core Processor Family DRAM Controller (rev 09)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port (rev 09)
00:01.1 PCI bridge: Intel Corporation Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port (rev 09)
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
00:16.0 Communication controller: Intel Corporation 6 Series/C200 Series Chipset Family MEI Controller #1 (rev 04)
00:1a.0 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Universal Host Controller #5 (rev 05)
00:1a.7 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #2 (rev 05)
00:1b.0 Audio device: Intel Corporation 6 Series/C200 Series Chipset Family High Definition Audio Controller (rev 05)
00:1c.0 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 1 (rev b5)
00:1c.1 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 2 (rev b5)
00:1c.2 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 3 (rev b5)
00:1d.0 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Universal Host Controller #1 (rev 05)
00:1d.7 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #1 (rev 05)
00:1f.0 ISA bridge: Intel Corporation HM65 Express Chipset LPC Controller (rev 05)
00:1f.2 SATA controller: Intel Corporation 6 Series/C200 Series Chipset Family 6 port Mobile SATA AHCI Controller (rev 05)
00:1f.3 SMBus: Intel Corporation 6 Series/C200 Series Chipset Family SMBus Controller (rev 05)
02:00.0 Ethernet controller: Broadcom Inc. and subsidiaries NetXtreme BCM57765 Gigabit Ethernet PCIe (rev 10)
02:00.1 SD Host controller: Broadcom Inc. and subsidiaries BCM57765/57785 SDXC/MMC Card Reader (rev 10)
03:00.0 Network controller: Broadcom Inc. and subsidiaries BCM4331 802.11a/b/g/n (rev 02)
04:00.0 FireWire (IEEE 1394): LSI Corporation FW643 [TrueFire] PCIe 1394b Controller (rev 08)
05:00.0 PCI bridge: Intel Corporation CV82524 Thunderbolt Controller [Light Ridge 4C 2010]
06:00.0 PCI bridge: Intel Corporation CV82524 Thunderbolt Controller [Light Ridge 4C 2010]
06:03.0 PCI bridge: Intel Corporation CV82524 Thunderbolt Controller [Light Ridge 4C 2010]
06:04.0 PCI bridge: Intel Corporation CV82524 Thunderbolt Controller [Light Ridge 4C 2010]
06:05.0 PCI bridge: Intel Corporation CV82524 Thunderbolt Controller [Light Ridge 4C 2010]
06:06.0 PCI bridge: Intel Corporation CV82524 Thunderbolt Controller [Light Ridge 4C 2010]
07:00.0 System peripheral: Intel Corporation CV82524 Thunderbolt Controller [Light Ridge 4C 2010]
```

**Comment by icefoxen** [comment] 2019-10-27 14:44
This looks like it is due to https://github.com/ggez/ggez/issues/579 where Wayland doesn't report the number of monitors correctly..  Unfortunately this is a bug upstream in the `winit` windowing library, see https://github.com/rust-windowing/winit/issues/793 .  The `devel` branch has a workaround that *might* help, give it a try if you want.

**Comment by bestouff** [comment] 2019-11-15 10:21
Same on Debian 10 FWIW.

**Comment by mwillsey** [comment] 2020-03-20 14:38
This seems to be a dupe of #579.

Anyway, I just found that the [arch wiki](https://wiki.archlinux.org/index.php/Wayland#winit) mentions a workaround: `WINIT_UNIX_BACKEND=x11`. This works for me!

**Comment by icefoxen** [comment] 2020-03-31 18:32
Yep, duplicate.  Thank you!

**Closed** 2020-03-31 18:32 UTC
Labels: Type-CODE, bug, duplicate
