### ISSUE TITLE
Rectangle offset from last drawn text

### ISSUE THREAD

**Issue by somewhen** [ggez/ggez#772] opened 2020-05-01 08:49 UTC
**Describe the bug**
If I draw a Text and then a rectangular Mesh, the latter is drawn relative to the position of the former. So for example, if I draw a rectangle at (0, 0) but I had previously drawn a Text at (24, 24), the rectangle will actually draw at (24, 24).

Other DrawParam parameters also seem to affect the rectangle, so for example if the Text is scaled by 2 the rect will also be scaled by 2. Drawing another Text is not affected by this bug.

**To Reproduce**
1. Draw text with a non-default DrawParam.
2. Draw a rectangle.

The rectangle will be affected by the text's DrawParam.

**Expected behavior**
I would expect that the rectangle's position is not affected by previous calls to `graphics::draw`. But maybe I'm missing something?

**Screenshots or pasted code**
```
let text = Text::new("Hello world!");
graphics::draw(ctx, &text, DrawParam::default().dest(Point2::new(200.0, 0.0)))?;

let rect = Rect::new(24.0, 24.0, 100.0, 100.0);
let mesh = graphics::Mesh::new_rectangle(ctx, graphics::DrawMode::fill(), rect, Color::from_rgb_u32(0x00FFFF))?;
// Actually draws at x = 224.
graphics::draw(ctx, &mesh, DrawParam::default())?;
```

It appears that adding these lines after drawing the text fixes the problem:
```
graphics::set_transform(ctx, DrawParam::default().to_matrix());
graphics::apply_transformations(ctx)?;
```

**Hardware and Software:**
 - ggez version: release 0.5.1
 - OS: Windows 10
 - Graphics card: Intel HD Graphics 520

**Comment by icefoxen** [comment] 2020-05-05 14:06
Probably a duplicate of #664 .  Thanks for the report!  I'll check it out.

**Comment by PsichiX** [comment] 2020-12-14 03:04
i had similar problem, where when i passed position to DrawParam via dest(), next thing rendered after this text had offset from this text item.
i had to fix this by enqueue text at position, then draw enqueued text immediately after:

```rust
graphics::queue_text(self.context, &text, [rect.left, rect.top], None);
graphics::draw_queued_text(
  self.context,
  graphics::DrawParam::default(),
  None,
  graphics::FilterMode::Linear,
)
```

https://github.com/PsichiX/raui/blob/master/raui-ggez-renderer/src/lib.rs#L342

**Comment by icefoxen** [comment] 2020-12-22 02:45
Closing as duplicate, will fix the linked issue.

**Closed by icefoxen** 2020-12-22 02:45 UTC
