### ISSUE TITLE
Cached_text reposition itself wrong

### ISSUE THREAD

**Issue by WEREMSOFT** [ggez/ggez#524] opened 2018-12-29 10:35 UTC
Environment: Mac osX Mojave 10.14.2

## Steps to reproduce ##

1. run 'cargo run --example cached_text'
2. Resize the window

## Expected Result ##
Text stays at top left corner.
<img width="636" alt="screen shot 2018-12-28 at 22 51 47" src="https://user-images.githubusercontent.com/808249/50537260-ad5e1900-0b5d-11e9-8ef9-75635c3e7423.png">

## Actual Result ##
Text centers vertically.

<img width="537" alt="screen shot 2018-12-29 at 11 35 06" src="https://user-images.githubusercontent.com/808249/50537275-d088c880-0b5d-11e9-81bc-bf4a893879d0.png">

**Comment by icefoxen** [comment] 2018-12-29 16:40
Thank you for the report!  I assume this is on the `master` branch?

There are [many irritating edge cases](https://github.com/ggez/ggez/issues/435) in the graphics coordinate code, unfortunately.  However, this one should get resolved in issue #493 .

**Comment by icefoxen** [comment] 2019-04-05 13:34
Actually, this is a duplicate of #553

**Closed by icefoxen** 2019-04-05 13:34 UTC
Labels: Type-CODE, bug
