### ISSUE TITLE
Empty resources directory is created when creating Context.

### ISSUE THREAD

**Issue by ceranco** [ggez/ggez#677] opened 2019-09-02 09:45 UTC
**Describe the bug**
When creating a `Context` using `ContextBuilder::build` an empty resource directory is created next to the application.

**To Reproduce**
Create an application with the following code and run it:
```rust
pub fn main() -> ggez::GameResult {
    let cb = ggez::ContextBuilder::new("resources-test", "Eran Cohen").window_setup(
        ggez::conf::WindowSetup::default()
    );
    let (ctx, event_loop) = &mut cb.build()?;
}
```
**Expected behavior**
Calling `ContextBuilder::build` should **not** create an empty resource directory.

**The source of the behavior**
By default, `ContextBuilder::load_conf_file` is set to `true`, so when `build` is called the following line in *context.rs* is run: (line 299)
```rust
fs.read_config().unwrap_or(self.conf)
```
`read_config` calls `is_file` (*filesystem.rs*, line 327) which then calls `vfs.metadata`(*filesystem.rs*, line 233) which then calls another `vfs.metadata` (*vfs.rs*, line 499) and brings us to *vfs.rs*, line 350: 

```rust
fn metadata(&self, path: &Path) -> GameResult<Box<dyn VMetadata>> {
    self.create_root()?;
    let p = self.to_absolute(path)?;
    p.metadata()
        .map(|m| Box::new(PhysicalMetadata(m)) as Box<dyn VMetadata>)
        .map_err(GameError::from)
}
```
which as can be seen, calls `create_root` and creates the directory.

**Hardware and Software:**
 - ggez version: *0.5.1*
 - OS: *Windows 10*, *Windows 7*
 - Graphics card: *Intel HD Graphics 530*
 - Graphics card drivers: *Intel*

**Workaround**
Creating a `Context` without trying to load from a configuration file doesn't create the directory:
```rust
let cb = ggez::ContextBuilder::new("life-rs", "Eran Cohen").with_conf_file(false);
```

**Comment by icefoxen** [comment] 2019-09-03 13:20
Currently, this is more or less as intended, since it saves the trouble of ever needing to check whether a resources directory exists.  So rather, the question seems to be, is this the behavior we want?  What would be preferable, and why?

**Comment by ceranco** [comment] 2019-09-05 05:42
Hi @icefoxen, thanks for the quick response. 

I personally don't like a seemingly innocent call like `ContextBuilder::build` ***creating*** a directory.
I'm not sure of the full ramifications, but perhaps the call to `metadata` can return an `Err()` if the resources directory doesn't exist?
At the least I think that the possible hidden side-effects of calling `ContextBuilder::build` should be documented.

**Comment by icefoxen** [comment] 2019-09-05 12:58
It should definitely at least be documented.  I'll take a look at it and see whether it can be simplified.

**Comment by piotrek-szczygiel** [comment] 2019-09-13 22:48
I would also really appreciate if no additional directory was created. My release build is baking in all resources into the executable and empty resources folder really annoys me.

**Comment by Andy-Python-Programmer** [comment] 2021-02-26 10:34
I am working on this.

**Comment by nobbele** [comment] 2021-05-30 15:31
vfs.rs:351 shouldn't call `self.create_root()`. It should return an Err, the root should be created in ContextBuilder so it's easier to manage. imo

**Comment by IGBC** [comment] 2021-06-04 10:05
This is now fixed.

**Closed by IGBC** 2021-06-04 10:05 UTC
Labels: *GOOD FIRST ISSUE*, Type-CODE, question
