### ISSUE TITLE
Scaling issue when resizing window on macOS

### ISSUE THREAD

**Issue by raybritton** [ggez/ggez#638] opened 2019-06-02 11:59 UTC
**Describe the bug**
When any ggez program is run and the window is resized the graphics appear incorrectly.

**To Reproduce**
Run this:
```
use ggez::{Context, ContextBuilder, GameResult, graphics};
use ggez::event::{self, EventHandler};
use ggez::conf::WindowMode;
use ggez::graphics::{MeshBuilder, DrawMode, Rect};
use ggez::mint::Point2;

fn main() {
    let (ctx, event_loop) = &mut ContextBuilder::new("resize_test", "Ray Britton")
        .window_mode(WindowMode {
            resizable: true,
            ..WindowMode::default()
        })
        .build()
        .expect("aieee, could not create ggez context!");

    let mut my_game = MyGame {};

    match event::run(ctx, event_loop, &mut my_game) {
        Ok(_) => println!("Exited cleanly."),
        Err(e) => println!("Error occured: {}", e)
    }
}

struct MyGame {}

impl EventHandler for MyGame {
    fn update(&mut self,_ctx: &mut Context) -> GameResult<()> { Ok(()) }

    fn draw(&mut self, ctx: &mut Context) -> GameResult<()> {
        graphics::clear(ctx, (0.,0.,0.,1.).into());

        let mesh = MeshBuilder::new()
            .rectangle(DrawMode::fill(), Rect::new(0.,0.,8.,8.), (1.,1.,1.,1.).into())
            .build(ctx)?;

        let size = graphics::window(ctx).get_inner_size().expect("failed to get window size");
        let dpi = graphics::window(ctx).get_hidpi_factor();

        let sw = (size.width * dpi) as f32;
        let sh = (size.height * dpi) as f32;

        graphics::draw(ctx, &mesh, (Point2 {x: 0., y: 0.},))?;
        graphics::draw(ctx, &mesh, (Point2 {x: sw - 8.,y: sh - 8.},))?;

        graphics::present(ctx)?;

        Ok(())
    }
}
```
and then resize the window

**Expected behavior**
The boxes should continue to appear in the corners of the window

**Screenshots or pasted code**
Initial window: 
<img width="512" alt="initial" src="https://user-images.githubusercontent.com/1632774/58760788-b7cd7600-8534-11e9-9c18-2fb466aa94f7.png">
If made bigger:
<img width="610" alt="bigger" src="https://user-images.githubusercontent.com/1632774/58760792-bdc35700-8534-11e9-86db-b86a2784641f.png">
If made smaller:
<img width="363" alt="smaller" src="https://user-images.githubusercontent.com/1632774/58760793-c156de00-8534-11e9-9db5-1d6f5a7d25a5.png">

**Hardware and Software:**
 - ggez version: 0.5.0-rc.2
 - OS: macOS Mojave 10.14.4, 13.3-inch (2560 x 1600) - DPI is 2
 - Graphics card: Intel Iris Plus Graphics 640

**Comment by icefoxen** [comment] 2019-06-03 17:15
Thank you for the bug report!  It might be related to #553 or that general class of problems.  I'll give it a try and see if I can reproduce.  The `graphics_settings` example might be useful to play with as well, pressing spacebar should toggle whether it tries to resize the contents of the window along with the window, so seeing whether that behaves properly or exhibits the same problem would be handy.

**Comment by raybritton** [comment] 2019-06-15 14:56
I wasn't sure what to look for so I record my screen while testing it. 
In the video:
I run the example, resize window, press space, resize window
Run the example again, press space, resize window

[mac scaling issues.zip](https://github.com/ggez/ggez/files/3293239/mac.scaling.issues.zip)

**Comment by PSteinhaus** [comment] 2021-05-22 07:39
I'd really like to know the state of this issue now.
A lot has changed in ggez considering hidpi-annoyances like this and my naive belief was that we now finally fixed it (though newest developments in #901 seem to prove me wrong...).

**Comment by jiyinyiyong** [comment] 2021-06-04 05:50
Since I don't see docs or example for how to handle `ScaleFactor` change events, I feel quite confused about how to handle this.

I have to monitors, one is macbook's retina screen(MacBook (Retina, 12-inch, 2017)), the other is a connected Dell screen. The window launched in macbook's screen looks scaled to half size:

![image](https://user-images.githubusercontent.com/449224/120752050-93e60600-c53b-11eb-9cc3-46854e1e78b6.png)

image's background is text in iTerm2.

and the window on Dell's monitor just look normal(larger).

![image](https://user-images.githubusercontent.com/449224/120751972-74e77400-c53b-11eb-89d7-a685cc509bd3.png)

And as I drag this window back and forth between these 2 screens, I see events:

```
Other window event fired: ScaleFactorChanged { scale_factor: 2.0, new_inner_size: PhysicalSize { width: 2000, height: 1200 } }
unkwnon event: RedrawRequested(WindowId(Id(140664462437040)))
Other window event fired: ScaleFactorChanged { scale_factor: 1.0, new_inner_size: PhysicalSize { width: 1000, height: 600 } }
```

while `width: 1000, height: 600` was the size I set to the window.

So is this supposed to be handled inside ggez, or supposed to handled by a user? If a user is responsible for handling it, can I find an example?

**Comment by IGBC** [comment] 2021-06-04 08:43
In short GGEZ is just a wrapper around some graphics frameworks, and other useful libraries. Scaling drawing is the User's job, as it is highly problem specific. 

Currently none of the GGEZ developers have a mac to test on, so while it technically works on mac os we are unable to provide support for it.

**Comment by PSteinhaus** [comment] 2021-06-04 09:06
> In short GGEZ is just a wrapper around some graphics frameworks, and other useful libraries. Scaling drawing is the User's job, as it is highly problem specific.

I don't completely agree. It is ggez policy to make sure that windows have the same physical size as set with ```ContextBuilder::window_mode```. This also applies to ```graphics::set_drawable_size```.

What confuses me is that your window looks smaller on your MacBook. I assume the ```scale_factor: 2.0, new_inner_size: PhysicalSize { width: 2000, height: 1200 }``` event is triggered when you move the window to your MacBook screen, correct? But If that's the case and the inner size changes (doubling the dimensions) then in the end it should still look the same... (or at least similiar).
Also, what we'd like to have (from ggez's point of view) is that the inner size of the window isn't changed at all i think.

Is a window created on the MacScreen smaller than one dragged to it? (I'd assume that this is the case, since you _should_ get a window with an inner size of width: 100, height: 600 then...

**Comment by jiyinyiyong** [comment] 2021-06-04 09:11
> the scale_factor: 2.0, new_inner_size: PhysicalSize { width: 2000, height: 1200 } event is triggered when you move the window to your MacBook screen, correct?

yes.

> Is a window created on the MacScreen smaller than one dragged to it? 

yes. window size halved if I create it in mac screen.

when I drag the window from Dell screen to mac screen, the window size remains, however the `x` `y` values in event changes.

**Comment by IGBC** [comment] 2021-06-04 09:18
yea I understand where you're comming from now. I had a similar problem in 0.5.1 on linux.

The scaling factor is creating a disparity between the physical size of the window (the actual number of pixels it has) versus the logical size of the window (the size in pixels / the scaling factor) This is actually a feature (although not one I like). You can use this hunk of cryptic code to translate the logical dimensions back into physical ones to get pixel perfect rendering control back:

```rust
    let dpi = graphics::window(ctx).get_hidpi_factor();
    let (wl, _): (f64, f64) = graphics::window(ctx).get_inner_size().unwrap().into();
    let (wp, hp): (f64, f64) = graphics::window(ctx)
        .get_inner_size()
        .unwrap()
        .to_physical(dpi)
        .into();
    let hp = hp * (wp / wl);
```
wp is the final physical width and hp is the physical height. multiply your logical x,y coordinates to get physical ones back.  Please note this code snippet is yanked out of an old commercial game project built on 0.5.1 so might need some tweaking to make work on 0.6

**Comment by PSteinhaus** [comment] 2021-06-04 09:33
> > Is a window created on the MacScreen smaller than one dragged to it?
> 
> yes. window size halved if I create it in mac screen.

Ah, now I understand. Sry, I read your first comment wrong. You already said there that a window **launched** on the MacBook screen looks smaller.

> when I drag the window from Dell screen to mac screen, the window size remains, however the `x` `y` values in event changes.

Ok this makes sense. When you drag it from Dell to Mac then the _actual_ window dimensions really double. It just looks to be the same size because of the retina display, which has double the pixel density. But actually the window grows to accomodate double the pixels in each dimension.

> The scaling factor is creating a disparity between the physical size of the window (the actual number of pixels it has) versus the logical size of the window

This is actually no longer true in the way it was in 0.5.1. In current devel (since #884 was merged) windows now get created with actual pixel sizes, not weird logical sizes anymore.

But when I made these changes I didn't think about users being able to drag the window between screens and what could happen then.

Your code snippet should be able to provide a workaround, but I think we should really take a look at why the window size changes at all and how we can avoid that.

**Comment by IGBC** [comment] 2021-06-04 09:37
> This is actually no longer true in the way it was in 0.5.1. In current devel (since #884 was merged) windows now get created with actual pixel sizes, not weird logical sizes anymore.

Oh thank god for that. In that case @jiyinyiyong Your code is actually behaving correctly. I would encourage you to develop your application to render its elements scaled proportional to the window size, as with the wide range of screen shapes and sizes available it's impossible to know what the exact window size of your app is going to be at design time.

**Comment by jiyinyiyong** [comment] 2021-06-04 09:46
my code is using `devel` branch so it's running `0.6.x`.

thanks, is `let dpi = graphics::window(ctx).get_hidpi_factor();` getting same value as `{ scale_factor: 2.0, ...}` that I use to render scaled proportional window size?

**Comment by PSteinhaus** [comment] 2021-06-04 09:49
> I would encourage you to develop your application to render its elements scaled proportional to the window size, as with the wide range of screen shapes and sizes available it's impossible to know what the exact window size of your app is going to be at design time.

True. In most cases it's best to use ```graphics::set_screen_coordinates``` to set the size at which you want to work and than just stay with that (that is, except you really really need pixel perfect control for some reason).

**Comment by PSteinhaus** [comment] 2021-06-04 09:50
> thanks, is `let dpi = graphics::window(ctx).get_hidpi_factor();` getting same value as `{ scale_factor: 2.0, ...}` that I use to render scaled proportional window size?

It should be, but I guess you should check to make sure.

**Comment by jiyinyiyong** [comment] 2021-06-04 10:07
tried several examples in `examples/`, I found same behavior(smaller window in mac screen):

https://github.com/ggez/ggez/blob/63e246d68bb400509134f217bc565fcd17df31e8/examples/logging.rs#L166-L173

and `.dimensions(640.0, 480.0)` is called before `ctx` is returned from the builder, which means I cannot use `graphics::window(ctx)` before building a window.

is there another way to get the correct physical size?

**Comment by PSteinhaus** [comment] 2021-06-04 10:09
This issue should affect each and every ggez project yes.
I'm afraid you can first correct the window size immediately after it was created.

**Comment by PSteinhaus** [comment] 2021-06-04 10:36
> ```rust
>     let dpi = graphics::window(ctx).get_hidpi_factor();
>     let (wl, _): (f64, f64) = graphics::window(ctx).get_inner_size().unwrap().into();
>     let (wp, hp): (f64, f64) = graphics::window(ctx)
>         .get_inner_size()
>         .unwrap()
>         .to_physical(dpi)
>         .into();
>     let hp = hp * (wp / wl);   // this line
> ```

What exactly does this line do though?
Shouldn't `to_physical(dpi)` already give us a fitting hp?

**Comment by PSteinhaus** [comment] 2021-06-04 10:45
I just started looking into this and strangely [we already seem to actively ignore these events in ggez](https://github.com/ggez/ggez/blob/e542c9fbc111d729b4220f9df31ee1a52a69d9b3/src/event.rs#L356-L358)...

But it seems that's not enough (or better: not the right way to handle this).
I guess we need to actively set the window size back to what it's supposed to be in this case then.
That's a bit annoying, but it should fix the issue.

A better way would of course be to change this behavior in the underlying window object, but I don't know if we can do that.

**Comment by PSteinhaus** [comment] 2021-06-04 10:56
Aha, I think we can in fact stop winit from doing any resizing at all. Take a look at what [the docs of this event](https://docs.rs/winit/0.23.0/winit/event/enum.WindowEvent.html#variant.ScaleFactorChanged) say:
> After this event callback has been processed, the window will be resized to whatever value is pointed to by the new_inner_size reference. By default, this will contain the size suggested by the OS, but it can be changed to any value.

So we should only need to actively set the new_inner_size back to the current window size.

**Comment by jiyinyiyong** [comment] 2021-06-04 11:05
does it mean we should use inner_size as well during window building?

```rust
    let window = WindowBuilder::new()
        .with_title("Hit space to toggle resizability.")
        .with_inner_size(LogicalSize::new(400.0, 200.0))
        .with_resizable(resizable)
        .build(&event_loop)
        .unwrap();
```
https://github.com/rust-windowing/winit/blob/1c4d6e7613c3a3870cecb4cfa0eecc97409d45ff/examples/resizable.rs#L15-L20

https://github.com/ggez/ggez/blob/e542c9fbc111d729b4220f9df31ee1a52a69d9b3/examples/logging.rs#L167-L174

**Comment by PSteinhaus** [comment] 2021-06-04 11:07
No, don't do that. `WindowMode::dimensions` does use that internally already (indirectly).

**Comment by jiyinyiyong** [comment] 2021-06-04 11:14
it's using PhysicalSize rather than LogicalSize?

```rust
let window_size = dpi::PhysicalSize::<f64>::from((window_mode.width, window_mode.height));
```

https://github.com/ggez/ggez/blob/devel/src/graphics/context.rs#L117-L122

**Comment by PSteinhaus** [comment] 2021-06-04 11:24
> update... tried locally and seem changing several PhysicalSize to LogicalSize fixes mac smaller behavior on my mac screen.

Getting a seemingly smaller window on a retina display IS expected behavior, so using changing PhysicalSize to LogicalSize in some places may give you a different behavior, but really not the one ggez wants to offer...

**Comment by PSteinhaus** [comment] 2021-06-04 11:25
> it's using PhysicalSize rather than LogicalSize?

Yes it is. As I said, ggez works with physical sizes only. We want windows to be exactly as big as specified in the window mode.

**Comment by jiyinyiyong** [comment] 2021-06-04 11:36
Does it break internals of ggez if I use `LogicalSize`? there's probably some reason, but as I user I found quite natural if (ideally) LogicalSize is used, I mean, windows appear with consistent sizes no matter which screen they are being launched, and the positions where click events happen are always consistent.

**Comment by PSteinhaus** [comment] 2021-06-04 11:48
If it works for you, great, change it and use it that way.
I'd spontaneously say that it probably does break some internals of ggez if you use `LogicalSize` instead of `PhysicalSize`...
You'd probably need to reverse most of #884 to get somewhat consistent behavior.

**Comment by PSteinhaus** [comment] 2021-06-04 11:52
But honestly... why do you want to use logical sizes instead of physical ones? Please believe us that it's a real pain to do so...

Instead you could just get the scale_factor of your window at startup and then scale your window size up by that and call `set_drawable_size` with that new size to get the bigger screen size that you want.

(Of course if you choose to keep using the devel branch then you'll also need to counteract the fix of the ScaleFactorChanged event that I'm currently trying to create.)

**Comment by jiyinyiyong** [comment] 2021-06-04 12:04
My previous experience are mostly webapps inside browsers so my first intuition on using sizes and position is how they behave in Chrome. I'm not sure about native apps. If I run a program in Chrome(or Electron), I just expect that the platform handles all that for me.

I'm not trying to keep a local branch. Tricks like `set_drawable_size` should be enough for my project(which is experimental), I need to get more familiar with winit for more usages and tricks.

**Comment by PSteinhaus** [comment] 2021-06-04 12:12
> I need to get more familiar with winit for more usages and tricks.

Good luck with that ^^
ggez for its part simply tries to counteract/remove all winit trickery, so that one can just trust in window sizes to be exactly as one specifies.

In webapps and the like things are a bit different of course. That's more akin to having a fullscreen window with ggez, where you just don't know how big it's going to be. For these cases `set_screen_coordinates` is the tool of choice.

**Comment by PSteinhaus** [comment] 2021-06-04 12:27
Ok with #949 merged windows should no longer change **physical** size when moving from one screen to another, so windows created on a screen are now as big as windows moved there.

**Comment by jiyinyiyong** [comment] 2021-06-04 12:27
Agreed. Special aspect of my project is I mostly using ggez as a renderer, and majors parts providing that are winit and lyon, and then comes ggez(back in my project using web tech, I used PIXI.js and I have to disable its internal loop for performance since I only paint interactively). So I still want to get familiar with winit.

Might be out of topic but I expected ggez to have better docs, or just more examples with comments. Feels a bit strange that I need to dig into issues and PR to find out detaisl about its behaviors. 😄

**Comment by PSteinhaus** [comment] 2021-06-04 12:54
> Might be out of topic but I expected ggez to have better docs, or just more examples with comments. Feels a bit strange that I need to dig into issues and PR to find out detaisl about its behaviors. 😄

What exactly do you mean? What should be better documented? We have no examples about hidpi because we actively counteract hidpi, so that you shouldn't have to care about it...

**Comment by jiyinyiyong** [comment] 2021-06-04 13:15
well, preconception of behaviors related to DPI from Web browsers...

**Comment by PSteinhaus** [comment] 2021-06-04 13:22
true, we should at least state that window sizes in ggez are alwas given in physical pixels not logical ones

**Comment by PSteinhaus** [comment] 2021-06-10 17:24
> 
> 
> I'd really like to know the state of this issue now.
> A lot has changed in ggez considering hidpi-annoyances like this and my naive belief was that we now finally fixed it (though newest developments in #901 seem to prove me wrong...).

Now that we've fixed the new bug @jiyinyiyong found, once again, I'd really like to know the state of the original issue.
If anyone owning a mac would please run the example code given [here](https://github.com/ggez/ggez/issues/638#issue-451183968) I'd be very thankful.

**Comment by jiyinyiyong** [comment] 2021-06-10 19:19
managed to compile after changing 2 lines more code for winit 24:

```rs
        let size = graphics::window(ctx).inner_size();
        let dpi = graphics::window(ctx).scale_factor();
```
dell screen with scale factor 1:

https://user-images.githubusercontent.com/449224/121583980-88c33680-ca63-11eb-868d-6e081d05806f.mov

for mac screen, I never found the point that was supposed to appear at bottom right:

![image](https://user-images.githubusercontent.com/449224/121584066-9e386080-ca63-11eb-9910-6fc3744257b5.png)

**Comment by PSteinhaus** [comment] 2021-06-11 08:51
Thanks @jiyinyiyong.
I had to change these lines, to get the code to work:
```rust
        let size = graphics::window(ctx).inner_size();
        let dpi = graphics::window(ctx).scale_factor() as f32;

        let sw = size.width as f32  * dpi;
        let sh = size.height as f32 * dpi;
```
Running the example I get exactly the same behaviour as you. I also tried it with a higher scaling factor and now think you should be able to find the white point on your mac screen by making the window a lot smaller.

All in all, this is expected behaviour. One shouldn't multiply by hand with the scale factor and then expect to get coordinates that make sense, since ggez screen space is by default measured in physical pixels.
So changing the mentioned lines into this:
```rust 
        let sw = size.width as f32;
        let sh = size.height as f32;
```
should fix the issue of the point not appearing at the bottom right initially.

When you resize the screen the screen coordinate system does not get updated automatically to conform to the new screen size. This behaviour is more or less a subjective choice, but it has the benefit of not unexpectatly interfering with camera systems or anything else a user might have set up to manage screen space.
So to get the point to always appear at the bottom right one needs to adapt the code to work like the [`graphics_settings`](https://github.com/ggez/ggez/blob/aed56921fbca8ac8192b492f0a46d92e4a0a95bb/examples/graphics_settings.rs#L165-L175) example. Which means that one needs to call `graphics::set_screen_coordinates` with a new Rect corresponding to the new window size.

If I apply both changes I get this code:
```rust
use ggez::{Context, ContextBuilder, GameResult, graphics};
use ggez::event::{self, EventHandler};
use ggez::conf::WindowMode;
use ggez::graphics::{MeshBuilder, DrawMode, Rect};
use ggez::mint::Point2;

fn main() {
    let (ctx, event_loop) = ContextBuilder::new("resize_test", "Ray Britton")
        .window_mode(WindowMode {
            resizable: true,
            ..WindowMode::default()
        })
        .build()
        .expect("aieee, could not create ggez context!");

    let mut my_game = MyGame {};
    event::run(ctx, event_loop, my_game);
}

struct MyGame {}

impl EventHandler for MyGame {
    fn update(&mut self,_ctx: &mut Context) -> GameResult<()> { Ok(()) }

    fn resize_event(&mut self, ctx: &mut Context, width: f32, height: f32) {
        println!("Resized screen to {}, {}", width, height);
        let new_rect = graphics::Rect::new(
            0.0,
            0.0,
            width,
            height,
        );
        graphics::set_screen_coordinates(ctx, new_rect).unwrap();
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult<()> {
        graphics::clear(ctx, (0.,0.,0.,1.).into());

        let mesh = MeshBuilder::new()
            .rectangle(DrawMode::fill(), Rect::new(0.,0.,8.,8.), (1.,1.,1.,1.).into())?
            .build(ctx)?;

        let size = graphics::window(ctx).inner_size();

        let sw = size.width as f32;
        let sh = size.height as f32;

        graphics::draw(ctx, &mesh, (Point2 {x: 0., y: 0.},))?;
        graphics::draw(ctx, &mesh, (Point2 {x: sw - 8.,y: sh - 8.},))?;

        graphics::present(ctx)?;

        Ok(())
    }
}
```
Running this I get what @raybritton initially defined as expected behaviour.
Please try to run it again and tell us if it works for you as well.

**Comment by jiyinyiyong** [comment] 2021-06-11 10:02
looks good now even after resized:

![image](https://user-images.githubusercontent.com/449224/121669431-e21c7b80-cade-11eb-8a66-a3efd7429851.png)

![image](https://user-images.githubusercontent.com/449224/121669458-e8aaf300-cade-11eb-9fc9-e37f9ee47296.png)

the only part that is strange is the bottom-right rect in my mac screen, that white rect is there but only a very small part is visible...

**Comment by PSteinhaus** [comment] 2021-06-11 10:25
> the only part that is strange is the bottom-right rect in my mac screen, that white rect is there but only a very small part is visible...

Hmm, that's strange indeed... Even with a scale factor of 2 I get nothing similiar to this. And to make it even stranger it seems like this once used to work, looking back at the screenshot of the initial window in the starting comment of this issue.
I've really no idea right now where this could come from, but it looks a bit like calculating the second mesh position like this could maybe fix it (for some reason):
```rust
graphics::draw(ctx, &mesh, (Point2 {x: sw - 8. * dpi,y: sh - 8. * dpi},))?;
```
But one would have to try this with meshes of varying dimensions though, I guess, like this:
```rust
let m_dim = mesh.dimensions(ctx).unwrap();

graphics::draw(ctx, &mesh, (Point2 {x: 0., y: 0.},))?;
graphics::draw(ctx, &mesh, (Point2 {x: sw - m_dim.w * dpi,y: sh - m_dim.h * dpi},))?;
```
If it really did, then I'd expect the error to grow from `0` in the top left corner to `dpi * width` or `dpi * height` respectively in the bottom right corner.

But then again, this is just a guess based of your screenshot and I see no reason why this should be the case, so I might well be wrong here.

**Comment by jiyinyiyong** [comment] 2021-06-11 10:37
```rs
graphics::draw(ctx, &mesh, (Point2 {x: sw - 8. * dpi,y: sh - 8. * dpi},))?;
```

true... or maybe just because macos use a too large border radius?

![image](https://user-images.githubusercontent.com/449224/121673828-e72ff980-cae3-11eb-9874-199f9fc60064.png)

**Comment by jiyinyiyong** [comment] 2021-06-11 12:25
agreed. no longer a bug. probably only some tips to mention on docs.

**Comment by PSteinhaus** [comment] 2021-06-11 14:16
> probably only some tips to mention on docs.

Agreed. Though I think with the latest updates to the docs, stating _everywhere_ that window sizes are given in physical sizes and the update to the FAQs I did to today, mentioning explicitly how [windows are created with physical sizes and a coordinate system matching it](https://github.com/ggez/ggez/blob/devel/docs/FAQ.md#gfx_resolution) I think we're good.

**Closed by PSteinhaus** 2021-06-11 14:16 UTC
Labels: Type-CODE, bug
