### ISSUE TITLE
Placing text in ggez 0.7

### ISSUE THREAD

**Issue by fenhl** [ggez/ggez#1008] opened 2022-01-17 14:56 UTC
I wrote [a wrapper](https://github.com/dasgefolge/sil/blob/abd4d42025859574ec7cfb1ba00b29fb776ba081/src/text.rs#L59-L90) for drawing text with a given size and alignment in ggez 0.6. It handles things like keeping a half-font-size margin from the edges of the window.

After upgrading to ggez 0.7, this broke, presumably due to [the changes to `DrawParam::offset`](https://github.com/ggez/ggez/blob/devel/docs/FAQ.md#offsets). Now text that's supposed to be centered on the window is instead centered on the right edge of the window so that only half of it is visible.

I've tried various fixes, but none seem to restore the intended behavior. My most recent attempt (from a different project, so some of the details are different):

```rust
pub(crate) fn draw(mut self, handler: &crate::Handler, ctx: &mut Context) -> GameResult {
    let Rect { w, h, .. } = graphics::screen_coordinates(ctx);
    for fragment in self.text.fragments_mut() {
        fragment.color.get_or_insert(self.color.unwrap_or(Color::WHITE));
    }
    self.text.set_font(handler.dejavu_sans, PxScale::from(self.size));
    self.text.set_bounds([w - self.size, h - self.size], self.halign);
    let dim = self.text.dimensions(ctx);
    self.text.draw(ctx, DrawParam::default().dest([ // upper left corner
        match self.halign {
            HorizontalAlign::Left => self.size / 2.0,
            HorizontalAlign::Center => (w - dim.w) / 2.0,
            HorizontalAlign::Right => w - self.size / 2.0 - dim.w,
        },
        match self.valign {
            VerticalAlign::Top => self.size / 2.0,
            VerticalAlign::Middle => (h - dim.h) / 2.0,
            VerticalAlign::Bottom => h - self.size / 2.0 - dim.h,
        },
    ]))
}
```

With this, text that should be centered looks like it's right-aligned instead.

Is there a way to make this work in ggez 0.7?

**Comment by PSteinhaus** [comment] 2022-01-17 21:14
Yes, there is. In fact you already link to [the solution](https://github.com/ggez/ggez/blob/devel/docs/FAQ.md#offsets):

> What this means for you is: If you want `DrawParam::offset` to be a relative offset (i.e. [1,1] means "bottom right", [0.5,0.5] means "centered", etc.) for any of the types mentioned as "absolute interpretations" above, then you'll have to adapt your offset like this:
```rust
// scale up and move the offset according to the dimensions of the Drawable
// the move is necessary as the dimensions (i.e. the bounding box) may not
// necessarily start at [0,0]
let mut new_param = param;
if let Transform::Values { offset, .. } = param.trans {
    if let Some(dim) = drawable.dimensions(ctx) {
        let new_offset = mint::Vector2 {
            x: offset.x * dim.w + dim.x,
            y: offset.y * dim.h + dim.y,
        };
        new_param = param.offset(new_offset);
    }
}
```

In your case this means: you have an object that demands absolute offsets (`Text`). To turn your relative offsets into working absolute offsets just multiply them with the dimensions of the text (so `=> 0.5` becomes `=> 0.5 * dim.x` or `=> * dim.y` in the vertical case for example).

**Comment by fenhl** [comment] 2022-01-18 07:53
I tried this fix and it didn't work, so I made [an example repo](https://github.com/fenhl/ggez-text-example/tree/d57378588da7dbb5a170b90066458b657c994d5c) demonstrating the issue to hopefully clarify.

Screenshot of `ex06`:

![screenshot of ex06](https://user-images.githubusercontent.com/641386/149893360-d04b7d63-8523-4627-a7ef-10843093bfdc.png)

Screenshot of `ex07`:

![screenshot of ex07](https://user-images.githubusercontent.com/641386/149893524-9f1bedd6-9906-4f2b-a3c6-3a0863911419.png)

**Comment by fenhl** [comment] 2022-01-18 07:57
Re-reading the FAQ entry, I also tried [something closer to the code shown there](https://github.com/fenhl/ggez-text-example/tree/a0719d7b08e3c405527e383447534d333f7f42f7), which also didn't work as expected:

![screenshot of ex07 with the new changes](https://user-images.githubusercontent.com/641386/149894157-50577d23-3584-4bdd-b585-188707450668.png)

**Comment by PSteinhaus** [comment] 2022-01-19 10:17
I'm sorry, I fiddled with this for quite a while yesterday before realizing that I mixed up (`dim.x`, `dim.y`) with (`dim.w`, `dim.h`) in my initial response.

Of course it needs to be `0.5 * dim.w` and `0.5 * dim.h` etc.

But, the strange thing is: That alone is still not enough to fix it...
If I do just that then I get:
![with_bounds](https://user-images.githubusercontent.com/40324631/150109564-097e68e2-5814-477d-8774-ec4b00662d46.png)

But if I also comment out `self.text.set_bounds([w - self.size, h - self.size], self.halign);` then I get this:
![without_bounds](https://user-images.githubusercontent.com/40324631/150109681-407ad174-ece0-4883-8ed1-f48e7fb45d65.png)

which is much closer to the 0.6 version and seems to do what you want to do.

The strange thing is: We haven't touched text much between between 0.6 and now, so I'm not sure how `set_bounds` (or `generate_varied_section` where the bounds are then actually used) might be at fault here...

**Comment by fenhl** [comment] 2022-04-18 11:14
Commenting out the `set_bounds` call is not an appropriate workaround since I sometimes need text to be displayed within a horizontally constrained area, with proper wrapping behavior.

**Comment by PSteinhaus** [comment] 2022-04-18 13:23
Sorry for that.
Could you perhaps try the fork of the currently open wgpu PR, to see whether the problem persists there?
It would require rewriting the example a bit, as the graphics API (and also the rest of it) has changed, though. I'll try to do so later today myself.

**Comment by fenhl** [comment] 2022-04-18 16:52
I'm having trouble getting anything to display on that branch, and its documentation seems to be outdated: the example uses `ggez::graphics::present`, which does not exist.

**Comment by PSteinhaus** [comment] 2022-04-18 17:46
Yeah, I'm sorry, I know it's a bit different and the docs are not yet as complete as they should be, but there is an [open PR](https://github.com/aleokdev/ggez/pull/4) for that fork that improves the docs quite a bit (I hope).

`graphics::present` has been removed. Now everything works based on `Canvas`es. You create one using `Canvas::from_frame`, draw onto it using `Canvas::draw_<something>` and then you call `Canvas::finish`, which works like `graphics::present`, except that you can create additional render passes, using other `Canvas`es, or even the same one, during the same frame. Take a look at the examples to see how this works exactly.

But, you don't really need to, to be honest. I'll be trying to get the thing to run after dinner.

**Comment by PSteinhaus** [comment] 2022-04-18 21:24
Ok, the good news is: I got it to run!
The bad news: The bug persists even in the rewrite, _but_ it changed: Now it affects the vertical alignment as well!

![still_buggy](https://user-images.githubusercontent.com/40324631/163879411-9fae5e14-c06e-4089-9d9b-549fc21c9aeb.png)

So, clearly text alignment is currently done wrong somehow...

Here is the code:
```rust
use {
    std::path::Path,
    ggez::{
        Context,
        ContextBuilder,
        GameError,
        GameResult,
        conf::{
            WindowMode,
            WindowSetup,
        },
        event::EventHandler,
        filesystem,
        graphics::{
            Color,
            DrawParam,
            Drawable as _,
            PxScale,
            Rect,
            Text,
            TextFragment,
            Transform,
        },
        timer,
    },
};
use ggez::graphics::{Canvas, CanvasLoadOp, FontData, TextAlign, TextLayout};

#[cfg(target_os = "linux")] const DEJAVU_PATH: &str = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf";
#[cfg(target_os = "windows")] const DEJAVU_PATH: &str = "\\Windows\\Fonts\\DejaVuSans.ttf";

struct TextBox {
    text: Text,
    size: f32,
    halign: TextAlign,
    valign: TextAlign,
}

impl TextBox {
    fn new(text: impl Into<TextFragment>) -> Self {
        Self {
            text: Text::new(text),
            ..Self::default()
        }
    }

    fn halign(mut self, halign: TextAlign) -> Self {
        self.halign = halign;
        self
    }

    fn valign(mut self, valign: TextAlign) -> Self {
        self.valign = valign;
        self
    }

    fn draw(mut self, handler: &crate::Handler, ctx: &mut Context, canvas: &mut Canvas) {
        let Rect { w, h, .. } = canvas.screen_coordinates().unwrap();
        self.text.set_font(handler.dejavu_sans.clone());
        self.text.set_scale(PxScale::from(self.size));
        self.text.set_bounds([w - self.size, h - self.size], TextLayout::Wrap { h_align: self.halign, v_align: self.valign });
        let param = DrawParam::default().dest([
            match self.halign {
                TextAlign::Begin => self.size / 2.0,
                TextAlign::Middle => w / 2.0,
                TextAlign::End => w - self.size / 2.0,
            },
            match self.valign {
                TextAlign::Begin => self.size / 2.0,
                TextAlign::Middle => h / 2.0,
                TextAlign::End => h - self.size / 2.0,
            },
        ]).offset([
            match self.halign {
                TextAlign::Begin => 0.0,
                TextAlign::Middle => 0.5,
                TextAlign::End => 1.0,
            },
            match self.valign {
                TextAlign::Begin => 0.0,
                TextAlign::Middle => 0.5,
                TextAlign::End => 1.0,
            },
        ]);
        let mut new_param = param;
        if let Transform::Values { offset, .. } = param.transform {
            let dim = self.text.measure(&mut ctx.gfx).unwrap();
            let new_offset = mint::Vector2 {
                x: offset.x * dim.x,
                y: offset.y * dim.y,
            };
            new_param = param.offset(new_offset);
        }
        self.text.draw(canvas, new_param);
    }
}

impl Default for TextBox {
    fn default() -> Self {
        Self {
            text: Text::default(),
            size: 100.0,
            halign: TextAlign::Middle,
            valign: TextAlign::Middle,
        }
    }
}

struct Handler {
    dejavu_sans: String,
}

impl Handler {
    fn new() -> GameResult<Self> {
        Ok(Self {
            dejavu_sans: "Dejavu".to_string(),
        })
    }
}

impl EventHandler<GameError> for Handler {
    fn update(&mut self, _: &mut Context) -> GameResult {
        Ok(())
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult {
        let mut canvas = Canvas::from_frame(&ctx.gfx, CanvasLoadOp::Clear(Color::BLACK));
        let (w, h) = ctx.gfx.drawable_size();
        canvas.set_screen_coordinates(Rect { x: 0.0, y: 0.0, w, h });
        let c = &mut canvas;
        TextBox::new("upper left").halign(TextAlign::Begin).valign(TextAlign::Begin).draw(self, ctx, c);
        TextBox::new("upper center").halign(TextAlign::Middle).valign(TextAlign::Begin).draw(self, ctx, c);
        TextBox::new("upper right").halign(TextAlign::End).valign(TextAlign::Begin).draw(self, ctx, c);
        TextBox::new("middle left").halign(TextAlign::Begin).valign(TextAlign::Middle).draw(self, ctx, c);
        TextBox::new("middle center").halign(TextAlign::Middle).valign(TextAlign::Middle).draw(self, ctx, c);
        TextBox::new("middle right").halign(TextAlign::End).valign(TextAlign::Middle).draw(self, ctx, c);
        TextBox::new("bottom left").halign(TextAlign::Begin).valign(TextAlign::End).draw(self, ctx, c);
        TextBox::new("bottom center").halign(TextAlign::Middle).valign(TextAlign::End).draw(self, ctx, c);
        TextBox::new("bottom right").halign(TextAlign::End).valign(TextAlign::End).draw(self, ctx, c);
        canvas.finish(&mut ctx.gfx)?;
        timer::yield_now();
        Ok(())
    }
}

fn main() -> GameResult {
    let (mut ctx, evt_loop) = ContextBuilder::new("ex07", "Fenhl")
        .window_setup(WindowSetup {
            title: format!("ggez 0.7 example"),
            ..WindowSetup::default()
        })
        .window_mode(WindowMode {
            resizable: true,
            ..WindowMode::default()
        })
        .build()?;
    #[cfg(windows)] filesystem::mount(&mut ctx, Path::new("C:\\"), true); // for font support
    #[cfg(not(windows))] filesystem::mount(&mut ctx, Path::new("/"), true); // for font support
    let handler = Handler::new()?;
    ctx.gfx.add_font("Dejavu", FontData::from_path(&ctx.fs, Path::new(DEJAVU_PATH))?);
    ggez::event::run(ctx, evt_loop, handler)
}
```

And, again, if I comment out `set_bounds` everything suddenly works as expected... annoying...

**Comment by PSteinhaus** [comment] 2022-04-18 21:33
Ok, the culprit seems to be the layouting.
If I comment out [this line](https://github.com/aleokdev/ggez/blob/09d138693f48177c850529a9e0ec13b96a6aec77/src/graphics/text.rs#L178) inside of `set_bounds`, then I can get expected behavior.

**Comment by PSteinhaus** [comment] 2022-04-18 21:51
Ah... no, I think I now realize what this is. It might be a breaking change, but I think it's actually working as intended.

The documentation of `set_bounds` states:
> Specifies rectangular dimensions to fit text inside of, wrapping where necessary. Within these bounds is also where text alignment occurs.

The second part is the interesting one here. I think it's all just a misunderstanding of what the _bounds_ actually are.
As these docs state, the bounds are the space where the alignment occurs. So if you say `set_bounds([w - self.size , h - self.size], ...)`, then you're really saying: "align my text relative to these bounds, which are basically the screen minus the font size". And this is exactly what happens:

- The top left case works out as expected, as it's not moved by alignment at all, in fact.
- The middle cases are actually placed where the bottom/right cases are supposed to be, as your `dest` places them at the middle of the screen, but the alignment box, starting there, is again almost as large as the screen, so placing them in the middle of that effectively places them at the corners of the screen.
- For the bottom/right cases this effect is of course doubled, pushing the text outside of the screen.

**Comment by PSteinhaus** [comment] 2022-04-18 22:05
Btw.: In both ggez 0.6 and ggez 0.7 the docs for `set_bounds` say:
> /// Specifies rectangular dimensions to try and fit contents inside of,
    /// by wrapping, and alignment within the bounds.  To disable wrapping,
    /// give it a layout with `f32::INF` for the x value.

So it's already made clear there, that the alignment is supposed to happen **within the bounds**. I'm sorry. Back then, I was so focused on offset stuff that I thought it just had to be that. I didn't even think to stop and actually read the docs...

**Comment by fenhl** [comment] 2022-04-19 12:17
My wrapper exists to abstract over several high-level text layout concerns, including handling horizontal and vertical alignment and adding some padding between the area where the text goes and the text itself (which is where that “half the font size” value comes from). The addition of vertical alignment in #1020 does indeed massively simplify the wrapper code. Unfortunately, the code does not run on my Raspberry Pi 3, giving an error of “failed to find suitable graphics adapter”. This error does not occur in the ggez 0.7 example.

**Comment by Vixeliz** [comment] 2023-06-30 07:24
Is this issue good to close looks like we have the solution here?

**Comment by sampullman** [comment] 2024-03-06 14:00
Closing, text layout appears to be working as intended.

**Closed by sampullman** 2024-03-06 14:00 UTC
Labels: bug
