### ISSUE TITLE
Confusion about DrawParam `offset` field 

### ISSUE THREAD

**Issue by ischeinkman** [ggez/ggez#736] opened 2020-01-16 02:55 UTC
I'm working on a pixel art-ish game and using a `SpriteBatch` to render groups of sprites at a time. Sometimes these renders include transforms on the batch itself, such as flipping the batch horizontally via scaling it by `[-1.0, 1.0]` from the center of the image. According to the documentation for `DrawParam::offset`, this should be doable via `offset([0.5, 0.5])`, a la:

```rust
let params = DrawParam::new()
    .scale([-1.0, 1.0])
    .offset([0.5, 0.5]);
graphics::draw(&mut ctx, &batch, params)?;
```

 However, that does not work. Instead, I need to scale by the dimensions of the batch itself: 

```rust
let batch_dims = batch.dimensions(&mut ctx).unwrap_or_else(Rect::zero);
let params = DrawParam::new()
    .scale([-1.0, 1.0])
    .offset([0.5 * batch_dims.w, 0.5 * batch_dims.h]);
graphics::draw(&mut ctx, &batch, params)?;
```

Is this intended behavior? If so, can the documentation be updated to reflect that?

**Comment by icefoxen** [comment] 2020-01-21 14:08
Nope, that's not intended behavior.  Thanks for reporting it!

**Comment by ischeinkman** [comment] 2020-01-22 00:20
I actually ended up looking through the examples and found [this](https://github.com/ggez/ggez/blob/efdab624d346532f913bc8b9096dffacb3effbb5/examples/spritebatch.rs#L72), so I ended up assuming it was intended and just not yet documented. Interesting to hear that it isn't.

Plus, I also ended up looking through the `DrawParam` source and becoming confused as to what the `offset` parameter is even supposed to do. The documentation says that the transform matrix is supposed to be `translate * offset * rotation * scale * offset_inverse`, but this means that the value of the top-left corner ends up being drawn at `self.translate + (Matrix4::identity() - scale) * self.offset` instead of `self.translate` or `self.translate - scale * self.offset`, which would be expected. 

I included the notebook I used for the algebra and a simple example [here.](https://gist.github.com/ischeinkman/fd8979abd69a43803111f19d9eba288e)

What *is* the intended behavior of the `offset` parameter? Should I create a new, more general issue/PR for general `offset` quirks?

**Comment by ischeinkman** [comment] 2020-02-02 22:43
@icefoxen Any update? At this point I've ended up writing my own "offset" style logic that I'd be happy to contribute if I could just get some direction on what the intended behavior of `offset` is. If I have source rect of `Rect { x: 0.0, y : 0.0, w : 1.0, h : 1.0}` and apply a transform of `DrawParam::new().scale([-2.0, -2.0]).offset([0.5, 0.5]).dest([10.0, 10.0])`, where is the top-left corner intended to be?

**Comment by LevitatingBusinessMan** [comment] 2020-04-22 03:22
I have been completely unable to rotate any square from its center. Seems like it's always rotating from the top left corner of the screen?? Maybe I am just doing something wrong I'll test further tomorrow.

**Comment by LevitatingBusinessMan** [comment] 2020-04-22 11:47
I was able to help my issue by moving the rectangle with the dest field in the DrawParam instead of setting a starting point in the Mesh itself.

**Comment by LevitatingBusinessMan** [comment] 2020-04-22 11:57
Actually, that didn't completely fix it. I also had to calculate the absolute offset.

```RS
        let player_mesh = graphics::Mesh::new_rectangle(
            ctx,
            graphics::DrawMode::fill(),
            graphics::Rect::new(0.0, 0.0, self.player.width, self.player.height),
            graphics::WHITE,
        )?;

        graphics::draw(
            ctx,
            &player_mesh,
            graphics::DrawParam::new()
                .dest([self.player.x, self.player.y])
                .offset([0.5 * self.player.width, 0.5 * self.player.height])
                .rotation(self.player.rotation)
        )?;
```

**Comment by Eosis** [comment] 2020-06-27 16:40
Hi all.

First off, great crate, maintainers! I haven't built any games before and this crate has made it super easy. 😁

For the issue at hand:
I think either behaviour is fine as long as the documentation reflects the API.
A very quick fix would be just to update the documentation to reflect the true offset behaviour if that is acceptable.

**Comment by PSteinhaus** [comment] 2021-02-04 12:43
> 
> 
> @icefoxen Any update? At this point I've ended up writing my own "offset" style logic that I'd be happy to contribute if I could just get some direction on what the intended behavior of `offset` is. If I have source rect of `Rect { x: 0.0, y : 0.0, w : 1.0, h : 1.0}` and apply a transform of `DrawParam::new().scale([-2.0, -2.0]).offset([0.5, 0.5]).dest([10.0, 10.0])`, where is the top-left corner intended to be?

@ischeinkman You are right that the offset logic was incorrect. #880 should fix it though. If you can please try to check whether offset now works as expected for you.

I just tested the spritebatch example and while it certainly changed in behavior the offset behavior for spritebatches is still not what you might expect. I think I know why though:

What ```offset``` actually does (at least now after the fix) is applying a negative translation before scaling and rotating and then finally translating the Drawable again (but this time without sign change and using ```dest```).

If you look at how a SpriteBatch is actually rendered you can see that it utilizes the given DrawParam to create a global transformation matrix. And this is where things get interesting:
- usually such transformations in ggez start off with a coordinate system of 1x1, allowing for an offset of 0,5x0,5 to mean "center"
- but in this case the transformation is applied directly to the global drawing surface, which means that the coordinate system starts off as surface_width x surface_height
This doesn't change how dest, scale, or rotation work, but it DOES change the behavior of offset.

I think we can and should fix this by changing ```SpriteBatch::draw``` to alter the offset, so that it scales itself accordingly using ```self.dimensions``` as pointed out by @ischeinkman.

But even then a tiny little problem remains and that is that ```SpriteBatch::dimensions``` is currently not working correctly when the sprites contained in it are rotated, as pointed out [here](https://github.com/ggez/ggez/issues/888), but if that gets fixed the spritebatch offset behavior could be finally fixed as well.

**Comment by PSteinhaus** [comment] 2021-02-04 16:19
Ok, I fixed this in #880 (which means I first fixed #888 and then changed ```SpriteBatch::draw``` to process an offset differently)
The new offset is now calculated like this:
```rust
                if let Some(dim) = self.dimensions(ctx) {
                    let new_offset = mint::Vector2 {
                        x: offset.x * dim.w + dim.x,
                        y: offset.y * dim.h + dim.y,
                    };
                    new_param = param.offset(new_offset);
                }
```
This makes the offset work as intended (meaning (0.5, 0.5) does now actually refers to the center of the spritebatch), but testing this I realised that calculating ```SpriteBatch::dimensions``` every frame is really costly. I therefore also added a check, so that this code only runs when there is an offset, saving most users from this cost.

Maybe @Eosis is right and it would be better to just change the docs...

**Comment by LevitatingBusinessMan** [comment] 2021-02-07 17:53
@PSteinhaus It took a year, but I guess that's fixed now. Is this going to break every game updating ggez though?

**Comment by PSteinhaus** [comment] 2021-02-07 21:06
@LevitatingBusinessMan
If they actively feed DrawParams with offsets != (0,0) to their spritebatches then yes.
If not they should be fine. The only place where spritebatches are actually used inside ggez (excluding examples) is in the rendering of text, but running the text example I don't see this causing any problems there.

**Comment by PSteinhaus** [comment] 2021-06-01 13:19
Fixed in #880.
I'm closing this now, but I'll certainly add this to the list of changes that we absolutely have to communicate when releasing 0.6.0.

**Comment by PSteinhaus** [comment] 2021-10-17 19:28
Ok, I'll reopen this now because I just realized my fix is not perfect.

The problem is: If the offset is relative, then (0., 0.) should mean "upper left corner".
This makes sense for sprites, but it can be annoying (or even catastrophic) for things like sprite-/meshbatches or single meshes, where you, as a user, build your mesh / place your sprites and then expect everything to be exactly where you placed it. But with the default offset being (0., 0.) suddenly everything would start shifted, so that DrawParam::dest matches the top left of your bounding box.

Currently in mesh- and spritebatch the way we handle it is to check whether the offset is (0., 0.) AND ONLY IF IT ISN'T we apply the shift I just mentioned (because in that situation it can be expected that the user actually WANTS his stuff to be shifted around to respect the given offset).

This though creates a nasty edge case when say someone sets DrawParam::offset dynamically to some changing value. As long as that value isn't (0., 0.) everything might behave as they expect, but if it happens to become (0., 0.) at some point then suddenly there is no bounding box respecting shift anymore!
So the problem is that the behaviour is not continuous. (0., 0.) is an edge case which is handled wildly differently than the rest.


How do we fix this?

The three options that I see are

- a) make offset absolute on batches and mesh again
- b) remove the edge case of (0., 0.) so that the bounding box respecting shift is always applied, which would also lead to reliable behaviour everywhere
- or c) let offset be relative everywhere, but just don't do this "bounding box respecting shift", i.e. instead of
```rust
let new_offset = mint::Vector2 {
    x: offset.x * dim.w + dim.x,
    y: offset.y * dim.h + dim.y,
};
```

do
```rust
let new_offset = mint::Vector2 {
    x: offset.x * dim.w,
    y: offset.y * dim.h,
};
```


`a` is annoying because it means offset works differently for different Drawables

`b` is expensive because it'd lead to ggez having to recalculate dimensions for the batches all the time AND it would also be annoying for those trying to use batches to just place things here and there expecting them to end up where they specified it, as noone expects that their scene is shifted to account for some bounding box they probably never even knew existed

`b` would also be a bit more work as we'd need to change how text is rendered as we currently too use a SpriteBatch with an offset of (0., 0.) for that.

`c` would mean that (0., 0.) wouldn't be "top left" anymore

**Comment by PSteinhaus** [comment] 2021-10-31 21:03
Having had a bit more time to think about this I'm now relatively sure that `a` is the only reasonable solution.

It's annoying because it leads to Drawables reacting differently towards `DrawParam`s, but it also makes sense because they also serve very different purposes asking for different kinds of offsets (at least most of the time).

It hurts to go back, but I hope it will yet be a step forward as well, because we can at least now put all of this reasoning in our documentation and take good care that we point people to it, through the documentation itself, as well as the docs on this repo.

For example, if we remove the relative offset from `MeshBatch` and `SpriteBatch` we should definitely put the implementation, together with a detailed explanation, in a document somewhere on this repo, so that people can easily implement relative offsets for themselves if they need them.

**Comment by PSteinhaus** [comment] 2021-11-04 22:50
With c791ad503b3bd51c4ef6b1527cf1d56979fad0d9 `a` is now officially the chosen behavior for the offset (again).

But, I also added a paragraph to the FAQs, explaining [how to still get relative or absolute offsets for any type of `Drawable`](https://github.com/ggez/ggez/blob/devel/docs/FAQ.md#offsets), if so desired, as well as some documentation on `Transform::offset` laying out the situation for our users.

**Closed by PSteinhaus** 2021-11-04 22:50 UTC
Labels: bug, question, Type-CODE
