### ISSUE TITLE
Random, filled areas when calling graphics::line() with random points.

### ISSUE THREAD

**Issue by pahhnv** [ggez/ggez#107] opened 2017-07-19 12:01 UTC
Hello,

I was trying out ggez when I came across the following problem when drawing lines with random points:

good:
<img src="https://user-images.githubusercontent.com/30288317/28361891-a378aed8-6c7a-11e7-8234-17f4ac06dc3a.png" height="300" width="400">
vs.
bad:
<img src="https://user-images.githubusercontent.com/30288317/28361945-d4b37ef6-6c7a-11e7-877e-9713dd2c5ebf.png" height="300" width="400">

A small example where this keeps happening:
```
fn draw(&mut self, ctx: &mut Context) -> GameResult<()> {
        graphics::clear(ctx);

        let total_points = 50;
	let fps = 1;
        let range = (50, 400);

        let mut rng = rand::thread_rng();
        let range = Range::new(range.0, range.1);

        let points: Vec<graphics::Point> = (0..total_points)
            .map(|_| {
                graphics::Point {
                    x: range.ind_sample(&mut rng) as f32,
                    y: range.ind_sample(&mut rng) as f32,
                }
            })
            .collect();

        graphics::line(ctx, &points)?;
        graphics::present(ctx);

        timer::sleep_until_next_frame(ctx, fps);
        Ok(())
    }
```
I'm getting these filled areas about every 4-5 frames/seconds. They differ in position and size but are mostly triangular. 

It doesn't matter if I generate the random points in draw() or beforehand and make sure they get passed to and are owned by MainState. 

I didn't find anything explaining this in the documentation or issues. What am I missing?

**Comment by icefoxen** [comment] 2017-07-19 14:50
Reproduced, happens pretty reliably even when you do only 2 total points.

I don't think you're missing anything; this is either a bug in `lyon`'s underlying tessellation, or in how we're using it (reusing state we shouldn't be between `line()` calls?  I doubt it, but maybe).

**Comment by pahhnv** [comment] 2017-07-19 16:38
I didn't find anything at https://bitbucket.org/rude/love/issues?status=new&status=open. I only had time to look at open issues though and I know nothing of tessellation or rater graphics in general. Let me know if I can provide you with any helpful information.

**Comment by icefoxen** [comment] 2017-07-19 16:54
Not sure what love2d would have to do with this since we don't actually share any code with it.

If you want to learn about tessellation and raster graphics, the relevant code is in `src/graphics/tessellation.rs` :D  It's a little labyrinthine but not actually super complicated, `lyon` does most of the heavy lifting.  It would be nice to at least know if the bug is in lyon or in ggez.

**Comment by pahhnv** [comment] 2017-07-19 17:06
Oh, I got that wrong. I subconsciously read Löve as Löwe which is the german word for lyon. Put that together with me not having looked at the real dependencies of ggez and you get me looking into some completely unrelated stuff ;)

There's https://github.com/nical/lyon/issues/114 which kind of sounds like what we saw. The stroke tessellator seems to be going nuts when the angle between two consecutive segments is very close to 180 degrees. Whatever that exactly means. The same issue for angles close to zero degrees has been fixed already.

**Comment by johalun** [comment] 2017-07-27 07:53
I experience this as well. There's no option to simple use glLine for simple line draws?

**Comment by johalun** [comment] 2017-07-28 09:22
Solved upstream: https://github.com/nical/lyon/issues/114

**Comment by icefoxen** [comment] 2017-07-31 15:48
The problem with glLine is that most GPU's don't support it very well and don't do anything other than single-pixel-wide lines.  It's something of a throwback and anyone who tries to use it for anything other than debugging is going to be disappointed.  :/

**Comment by johalun** [comment] 2017-07-31 17:08
Yeah I know glLine is not optimal but as a fallback I could use it. However, lyon is fixed now so no need.

**Comment by icefoxen** [comment] 2017-08-20 15:09
This should be fixed in master thanks to a Lyon upgrade

**Closed** 2017-08-25 15:23 UTC
Labels: *LESS EASY*, bug, [CODE]
