### ISSUE TITLE
get_current_monitor panics on Wayland (Sway)

### ISSUE THREAD

**Issue by knightshrub** [ggez/ggez#670] opened 2019-08-05 04:49 UTC
**Describe the bug**
The example `01_super_simple` and `02_hello_world` panic when running on Wayland (Sway as compositor).
`cargo run --example 02_hello_world --release`

The panic is caused by `get_current_monitor` in 1

**To Reproduce**
Run `cargo run --example 02_hello_world --release`

**Error message**
```
$ RUST_BACKTRACE=1 cargo run --example 02_hello_world --release
    Finished release [optimized] target(s) in 0.24s
     Running `target/release/examples/02_hello_world`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic
             at src/libcore/panicking.rs:49
   9: winit::platform::platform::wayland::window::Window::get_current_monitor
  10: ggez::graphics::context::GraphicsContextGeneric<B>::set_window_mode
  11: ggez::graphics::context::GraphicsContextGeneric<ggez::graphics::GlBackendSpec>::new
  12: ggez::context::ContextBuilder::build
  13: _02_hello_world::main
  14: std::rt::lang_start::{{closure}}
  15: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  17: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  18: main
  19: __libc_start_main
  20: _start
```

**Hardware and Software:**
 - ggez version: current git master, also happens in own hello world on crates.io 0.5
 - OS: Linux (5.2.5-arch1-1-ARCH)
 - Graphics card: Intel graphics (Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series Integrated Graphics)

**Comment by icefoxen** [comment] 2019-08-05 17:09
Thank you for the bug report!  However, this is a duplicate of #579 .

**Closed** 2020-01-28 17:36 UTC
Labels: duplicate
