### ISSUE TITLE
[Question] How can I clip a Mesh or other screen area based on supplied bounds?

### ISSUE THREAD

**Issue by hughlang** [ggez/ggez#603] opened 2019-03-12 16:29 UTC
I want to create a vertical scrollable region inside of specified Rect and I would like the content that exceeds the bounds of the area to be masked. 

I found this issue #468, but it doesn't help since I am not working with a tile map or spritebatch. I have tried using the Canvas to draw things off screen, but it is slow and seems buggy. 

Some ideas of what could help me:

* If MeshBuilder or Mesh had a clipping function, 
  * I could use that around the entire scrollable viewport. 
  * Or I could use that to clip items at the edge of the viewport, so that they do not overflow outside the bounds.
* If there was something like SpriteBatch that works with random mesh types and text and use that to draw only the desired "src" Rect
* An example that shows how to use the gfx pipeline or whatever to do this.
* If Canvas supported smaller off-screen windows that were much more performant. 

If you have some ideas, let me know. Thanks!

**Comment by icefoxen** [comment] 2019-03-12 22:38
That's a good question. Canvas is indeed the first thing that comes to mind, and there's an example that demonstrates doing just that, but... Yes, it is still somewhat buggy. :( I don't think it should be particularly slow though, can you share an examplr or explain your use case more?

The problem is basically that, afaik, we have to get the graphics card to do the clipping for us. I believe the proper way to do that is with the scissor functions, which currently ggez resolutely ignores. I'll do some research though and see what I can turn up.

**Comment by hughlang** [comment] 2019-03-13 14:45
Hi @icefoxen,

My use case is building a full range of GUI components, which is madness, but I'm gonna try anyway. So the component I'm working on now is a list box, that scrolls to display rows. I might try the Canvas approach again later, but I decided to make it simple and not show scrolling with animation. It only shows full rows. 

Nonetheless, I would still like to see some ways of clipping rectangular content or even non-rectangular like rounded corner clipping. I soon need to create a text area with scrollable content. And recently, I was working on a text field input box, which has clipping needs since any text that is longer than the input field will go out of bounds. 

thanks

**Comment by icefoxen** [comment] 2019-03-13 15:53
Oh snap, a GUI library?  Is it going to be open source?  Can I see what you have so far somewhere?  :hype:

Well, the *easy* way to "clip" things in ggez is to draw other stuff on top of them, so far.  As I said, I'll have to do a bit of research to see what the *best* way to do it is.  I know that Firefox and Wayland and other such compositor-y systems do a *lot* of rendering to texture and then essentially drawing pieces of that texture, but they are complicated and ggez's render-to-texture functionality, as you have noticed, currently kinda sucks.  So it'd be nice to be able to do better.

**Comment by hughlang** [comment] 2019-03-13 16:06
It's here: https://github.com/wasm-network/tweek-rust

It was designed mainly as an animation library, but then I started having fun building UI components. The master branch just has some experimental things like buttons with hover animation. Try out the two examples to see.

I am currently building the entire GUI library in the ui-components branch. That's not ready to look at yet.

**Comment by termhn** [comment] 2019-03-13 17:25
I believe the best way to do this is to use masks. However, that's not something that's really supported by ggez natively. The basic idea would be that you'd pretty much copy the spritebatch code, except you'd add an extra texture which would contain white and black (and in between) pixels. Then in the fragment shader you'd sample this mask texture based on the current screen coordinate and apply it to the alpha of the output, i.e. vertex:

```glsl
#version 150 core

in vec2 a_Pos;
in vec2 a_Uv;
in vec4 a_VertColor;

in vec4 a_Src;
in vec4 a_TCol1;
in vec4 a_TCol2;
in vec4 a_TCol3;
in vec4 a_TCol4;
in vec4 a_Color;

layout (std140) uniform Globals {
    mat4 u_MVP;
};

out vec2 v_Uv;
out vec2 v_ScreenUv;
out vec4 v_Color;

void main() {
    v_Uv = a_Uv * a_Src.zw + a_Src.xy;
    v_Color = a_Color * a_VertColor;
    mat4 instance_transform = mat4(a_TCol1, a_TCol2, a_TCol3, a_TCol4);
    vec4 position = instance_transform * vec4(a_Pos, 0.0, 1.0);

    vec4 proj_position = u_MVP * position;
    v_ScreenUv = proj_position.xy * 0.5 + vec2(0.5, 0.5);
    gl_Position = proj_position;
}
```
Fragment
```glsl
 #version 150 core

uniform sampler2D t_Texture;
uniform sampler2D t_Mask;
in vec2 v_Uv;
in vec4 v_Color;
in vec2 v_ScreenUv;
out vec4 Target0;

layout (std140) uniform Globals {
    mat4 u_MVP;
};

void main() {
    vec4 color = texture(t_Texture, v_Uv) * v_Color;
    float alpha = texutre(t_Mask, v_ScreenUv);
    Target0 = vec4(color.rgb, alpha);
}
```

**Comment by OvermindDL1** [comment] 2019-03-13 17:54
Wouldn't the traditional way to do this be a normal OGL Clipping bound?  Which you can emulate in a shader inefficiently as well.

**Comment by hughlang** [comment] 2019-03-14 12:00
@termhn 

Hey, I like the idea you are suggesting if i understand correctly. Creating something like SpriteBatch that deals with meshes and other drawables? 

Is it feasible? I lack the skills to convert your opengl code sample into a solution though.

thx

**Comment by PSteinhaus** [comment] 2021-06-12 08:20
> I want to create a vertical scrollable region inside of specified Rect and I would like the content that exceeds the bounds of the area to be masked.
> I have tried using the Canvas to draw things off screen, but it is slow and seems buggy.

>     * If Canvas supported smaller off-screen windows that were much more performant.

> I would still like to see some ways of clipping rectangular content or even non-rectangular like rounded corner clipping.

It's probably too late for you now, but reading all this I think @termhn 's solution might be the best overall, if one manages to get it to work.

For an easier (but less performant way) of doing this you could of course achieve all of this by
- creating two canvases of the size of your clipping region
- drawing the things you want to clip onto the first one
- drawing a white mesh (being whatever mask you want) onto the second one
- and then drawing the second canvas onto the first using the `Multiply` blend mode
- then you have your clipped content and can just draw it onto the screen (or onto another canvas) using the new `Premultiplied` blend mode

I haven't tested it, so I can't say whether this would actually be a way to go, but what I can say is that canvases are now (meaning in the current devel branch) working mostly as expected. We managed to fix most of their nasty bugs, though some things like #695 still remain to be fixed.

Since this thread has been dead for two years I'm closing it now, but of course feel free to reopen it if you're still working on it and have more questions or feedback.

**Comment by gzhynko** [comment] 2022-05-13 13:19
Hey! Now that #1020 is merged (thanks to everyone who worked on that, by the way!), is there a better way to achieve mesh clipping/scissoring? It seems like WGPU's `RenderPass` allows setting a scissor rectangle via [`set_scissor_rect`](https://github.com/gfx-rs/wgpu/blob/c1934dc07f39f8643471f8b40cf62f47fd56c9a6/wgpu/src/lib.rs#L2779), maybe `Canvas` could expose that method?

**Comment by PSteinhaus** [comment] 2022-05-13 22:08
That's a good hint, thanks. I'll reopen this, as this seems worthwhile to me.

**Comment by PSteinhaus** [comment] 2022-05-19 17:42
Now that #1032 and #1034 are merged I think we can safely close this.
Thanks for the addition!

**Closed by PSteinhaus** 2022-05-19 17:42 UTC
