### ISSUE TITLE
Wrong window dimensions, unwanted scaling (Linux, X11)

### ISSUE THREAD

**Issue by gardrek** [ggez/ggez#615] opened 2019-04-02 03:36 UTC
The window size by default should be 800x600, but when I run my game it comes out as 867x650. This same scaling factor happens if I use `ggez::ContextBuilder.window_mode` to set the dimensions; it always ends up 8.33% bigger than what I set. The scale of the "screen coordinates" however appears to stay at 800x600, causing anything drawn to be scaled as well. E.g. drawing a 128x128 input image results in a 138x138 output, with scaling artifacts. This may be related to my other issue #613.

Workaround:
Setting WINIT_HIDPI_FACTOR=1 causes the correct behavior. It seems this is a hidpi issue after all.

Notes:
 • setting `hidpi` true or false has no effect
 • setting min_dimensions and max_dimensions seems to be affected the same way; when setting them to 800x600 each the window cannot be resized from 867x650
 • `graphics::os_hidpi_factor()` gives 1.0833334

**Comment by icefoxen** [comment] 2019-04-02 15:23
Duplicate of: #539

Useful data point tthough, thank you.

**Closed by icefoxen** 2019-04-02 15:23 UTC

**Comment by sigod** [comment] 2019-10-05 16:21
#539 was closed because Mac support was dropped. But _this_ issue is about Linux.

**Comment by PSteinhaus** [comment] 2021-05-22 08:04
@sigod You're absolutely right. Since a similiar issue popped back up in #901 I'd still label this a duplicate and keep it closed though. Also, for most people this issue _should_ have been fixed in #884, since it was able to fix things like #883 and #890.
