### ISSUE TITLE
PopOS Mouse Movement Causes Panic

### ISSUE THREAD

**Issue by cowboy8625** [ggez/ggez#919] opened 2021-04-02 03:59 UTC
**Describe the bug**
When building on Pop OS some times the ggez window will pop up and stay and you can play the game but if you move mouse the game crashes and then it will not open again.  I have my tiling window manager on and I turned it off but that did not seem to effect it.

**To Reproduce**
you can find the snake game i used [here](https://github.com/cowboy8625/ggez_snake) just rebuild on Pop OS

**Expected behavior**
I am not 100% sure how to repoduse this bug but while the game is starting up seem to help not to move mouse as when or if the ggez_snake window opens moving mouse crashes it. 

**Panic Error**
```
thread 'main' panicked at 'attempted to leave type `platform::platform::x11::util::input::PointerState` uninitialized, which is invalid', /home/cowboy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:659:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:50:5
   3: winit::platform::platform::x11::util::input::<impl winit::platform::platform::x11::xdisplay::XConnection>::query_pointer
   4: winit::platform::platform::x11::EventsLoop::process_event
   5: ggez::event::run
   6: ggez_snake::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Hardware and Software:**
 - ggez version:  0.5.1
 - OS: POP OS (Debian)
 - Graphics card: Intel® Iris® Xe Graphics

**Comment by OvermindDL1** [comment] 2021-04-06 15:03
Same on a couple of other X11 based distros that I've tested on in the past day as well, seems to be a ggez issue, not a distro issue.

**Comment by cowboy8625** [comment] 2021-04-10 20:10
ok good to know.

**Comment by ccb23** [comment] 2021-04-11 08:32
On my system I am able to reproduce this issue by starting `03_drawing` example:
**steps to reproduce**:
1) ` cargo run --package ggez --example 03_drawing`
2) move mouse pointer over game window

**Hardware and Software**:
- ggez: version 0.5.1
- OS: arch linux / gnome-shell 40.0 (X11)
- Graphics card: Intel HD Graphics (Dell XPS 9360)

**Stack-Trace**:
`
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::panicking::panic
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
   3: core::mem::uninitialized
             at /home/christoph/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:658
   4: winit::platform::platform::x11::util::input::<impl winit::platform::platform::x11::xdisplay::XConnection>::query_pointer
             at /home/christoph/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/x11/util/input.rs:94
   5: winit::platform::platform::x11::EventsLoop::process_event
             at /home/christoph/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/x11/mod.rs:956
   6: winit::platform::platform::x11::EventsLoop::poll_events
             at /home/christoph/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/x11/mod.rs:270
   7: winit::platform::platform::EventsLoop::poll_events
             at /home/christoph/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/mod.rs:522
   8: winit::EventsLoop::poll_events
             at /home/christoph/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/lib.rs:277
   9: ggez::event::run
             at ./src/event.rs:175
  10: _03_drawing::main
             at ./examples/03_drawing.rs:188
  11: core::ops::function::FnOnce::call_once
`

**Comment by PSteinhaus** [comment] 2021-04-11 16:09
Can you test whether this issue also affects the current devel branch? (I know, it doesn't build due to a missing comma, but there is a PR that fixes it and thus builds.)
The devel branch uses an updated version of winit.

If it persists then I'd try to build winit and run some of their examples (something with mouse input preferably).
If you could reproduce the error there, then we could just report the issue there.

**Comment by ccb23** [comment] 2021-04-11 20:12
I just double checked with devel-fix-PR:
https://github.com/dchiquito/ggez/tree/fix-build

unfortunately it crashes right at startup (even without mouse over the window), looks like another crash, though:

```
cargo run --package ggez --example 03_drawing                                                                                                                101 ↵ devel
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/examples/03_drawing`
Requested OpenGl 3.2 Core profile, actually got Driver vendor: Intel, renderer Mesa Intel(R) HD Graphics 620 (KBL GT2), version 4.6, shading language 4.60.
thread 'main' panicked at 'not implemented', ~/rust/ggez-ng2/src/graphics/mesh.rs:182:21
stack backtrace:
   0:     0x558210bb3980 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x558210bb3980 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x558210bb3980 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x558210bb3980 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x558210bd6b5c - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x558210bafae2 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x558210bb610d - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x558210bb610d - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x558210bb610d - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x558210bb5db8 - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x558210bb67f1 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x5582108201ec - std::panicking::begin_panic::{{closure}}::hed217c19597944f8
                               at ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:506
  12:     0x558210820cc9 - std::sys_common::backtrace::__rust_end_short_backtrace::h404f47e44c2410b9
                               at ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:153
  13:     0x558210820117 - std::panicking::begin_panic::he08a5effe244085b
                               at ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:505
  14:     0x55820ff9cd2d - ggez::graphics::mesh::MeshBuilder::ellipse::hf4677140513296db
                               at ~/sandbox/rust/ggez-ng2/src/graphics/mesh.rs:182
  15:     0x55820ffa2127 - _03_drawing::build_mesh::h596ee1a12d6c635c
                               at ~/sandbox/rust/ggez-ng2/examples/03_drawing.rs:56
  16:     0x55820ffa135c - _03_drawing::MainState::new::h5d297c4cb4ef57a2
                               at ~/sandbox/rust/ggez-ng2/examples/03_drawing.rs:28
  17:     0x55820ffa4a12 - _03_drawing::main::h99eef7c785e1db24
                               at ~/sandbox/rust/ggez-ng2/examples/03_drawing.rs:184
  18:     0x55820ff92422 - core::ops::function::FnOnce::call_once::hcc7777db4d435386
                               at ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  19:     0x55820ffb8b0a - std::sys_common::backtrace::__rust_begin_short_backtrace::h4a557bf5a3657e84
                               at ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
  20:     0x55820ffb8ad6 - std::rt::lang_start::{{closure}}::h6bd35dc5b5cb9536
                               at ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66
  21:     0x558210bb6c17 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he179d32a5d10d957
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:259
  22:     0x558210bb6c17 - std::panicking::try::do_call::hcb3d5e7be089b2b4
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381
  23:     0x558210bb6c17 - std::panicking::try::h7ac93b0cd56fb701
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345
  24:     0x558210bb6c17 - std::panic::catch_unwind::h7b40e396c93a4fcd
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
  25:     0x558210bb6c17 - std::rt::lang_start_internal::h142b9cc66267fea1
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51
  26:     0x55820ffb8aa7 - std::rt::lang_start::h2f9f2932c027f88e
                               at ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65
  27:     0x55820ffa4aea - main
  28:     0x7f669cf57b25 - __libc_start_main
  29:     0x55820ff8209e - _start
  30:                0x0 - <unknown>

```

**Comment by PSteinhaus** [comment] 2021-04-12 07:46
Haha, progress!
The crash is caused by the fact that filled ellipses are unavailable as of now, due to a bug/missing functionality in a former version of lyon.

Luckily there's another PR by dchiquito #918 which fixes this.
Let's see how the error changes ^^

**Comment by ccb23** [comment] 2021-04-12 08:26
Nice, that's it. Your inspired guess was just right. devel-branch + #918 + #917 is working for me, without any mouse issues.

**Comment by ccb23** [comment] 2021-04-12 09:06
I found this issue for older Versions on winit's issue list: [mouse-issue](https://github.com/rust-windowing/winit/issues/1778)

**Comment by PSteinhaus** [comment] 2021-04-12 09:18
> I found this issue for older versions on winit's issue list: [1778](https://github.com/rust-windowing/winit/issues/1778)

Perfect, thanks! Then we don't even have to report it and can hopefully safely close this when #917 and #918 get merged :)

**Closed** 2021-05-21 10:48 UTC
