### ISSUE TITLE
`context::tests::has_traits` fails due to event loop outside of main thread

### ISSUE THREAD

**Issue by 0----0** [ggez/ggez#1136] opened 2022-11-05 17:29 UTC
**Describe the bug**
Running tests results in this error from `context::tests::has_traits`:
```
test context::tests::has_traits ... FAILED

failures:

---- context::tests::has_traits stdout ----
thread 'context::tests::has_traits' panicked at 'Initializing the event loop outside of the main thread is a significant cross-platform compatibility hazard. If you absolutely need to create an EventLoop on a different thread, you can use the `EventLoopBuilderExtWindows::any_thread` function.', C:\Users\Asc\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop.rs:191:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**
`cargo test`

**Hardware and Software:**
 - ggez version: 0.8.1
 - OS: Windows 11
 - Graphics card: Radeon 6900 XT

**Comment by nobbele** [comment] 2022-11-05 20:26
Duplicate of #933

**Closed by nobbele** 2022-11-05 20:26 UTC
