### ISSUE TITLE
Setting shader params twice does nothing

### ISSUE THREAD

**Issue by 0----0** [ggez/ggez#1137] opened 2022-11-05 18:29 UTC
**Describe the bug**
If I draw two meshes with the same shader, but different parameters on each shader, the first set of parameters is used for both meshes.

**To Reproduce**
```rust
//! A very simple shader example.

use crevice::std140::AsStd140;
use ggez::event;
use ggez::glam::Vec2;
use ggez::graphics::{self, Color, DrawMode};
use ggez::{Context, GameResult};
use std::env;
use std::path;

#[derive(AsStd140)]
struct Dim {
    rate: f32,
}

struct MainState {
    dim: Dim,
    shader: graphics::Shader,
    params: graphics::ShaderParams<Dim>,
}

impl MainState {
    fn new(ctx: &mut Context) -> GameResult<MainState> {
        let dim = Dim { rate: 0.5 };
        let shader = graphics::ShaderBuilder::new_wgsl()
            .fragment_path("/dimmer.wgsl")
            .build(&ctx.gfx)?;
        let params = graphics::ShaderParamsBuilder::new(&dim).build(&mut ctx.gfx);
        Ok(MainState {
            dim,
            shader,
            params,
        })
    }
}

impl event::EventHandler<ggez::GameError> for MainState {
    fn update(&mut self, ctx: &mut Context) -> GameResult {
        self.dim.rate = 0.5 + (((ctx.time.ticks() as f32) / 100.0).cos() / 2.0);
        Ok(())
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult {
        let mut canvas = graphics::Canvas::from_frame(ctx, Color::from([0.1, 0.2, 0.3, 1.0]));

        let circle = graphics::Mesh::new_circle(
            ctx,
            DrawMode::fill(),
            Vec2::new(100.0, 300.0),
            100.0,
            2.0,
            Color::WHITE,
        )?;
        canvas.draw(&circle, Vec2::new(0.0, 0.0));

        self.params.set_uniforms(ctx, &self.dim);
        canvas.set_shader(self.shader.clone());
        canvas.set_shader_params(self.params.clone());
        let circle = graphics::Mesh::new_circle(
            ctx,
            DrawMode::fill(),
            Vec2::new(400.0, 300.0),
            100.0,
            2.0,
            Color::WHITE,
        )?;
        canvas.draw(&circle, Vec2::new(0.0, 0.0));

        let uniforms = Dim {
            rate: self.dim.rate * 0.5,
        };
        let params = graphics::ShaderParamsBuilder::new(&uniforms).build(&mut ctx.gfx);
        canvas.set_shader_params(params);
        let circle = graphics::Mesh::new_circle(
            ctx,
            DrawMode::fill(),
            Vec2::new(700.0, 300.0),
            100.0,
            2.0,
            Color::WHITE,
        )?;
        canvas.draw(&circle, Vec2::new(0.0, 0.0));

        canvas.finish(ctx)
    }
}

pub fn main() -> GameResult {
    let resource_dir = if let Ok(manifest_dir) = env::var("CARGO_MANIFEST_DIR") {
        let mut path = path::PathBuf::from(manifest_dir);
        path.push("resources");
        path
    } else {
        path::PathBuf::from("./resources")
    };

    let cb = ggez::ContextBuilder::new("shader", "ggez").add_resource_path(resource_dir);
    let (mut ctx, event_loop) = cb.build()?;

    let state = MainState::new(&mut ctx)?;
    event::run(ctx, event_loop, state)
}
```

**Expected behavior**
The rightmost circle should have half the brightness of the middle circle.

**Screenshots or pasted code**
![image](https://user-images.githubusercontent.com/9070490/200135388-ee78ce62-45fe-4b30-9cf9-d575f9662b27.png)

**Hardware and Software:**
 - ggez version: 0.8.1
 - OS: Windows 11
 - Graphics card: Radeon 6900 XT

**Comment by PSteinhaus** [comment] 2022-11-05 18:36
This is most certainly caused by #1129 
ShaderParams are another place where `wgpu::Queue::write_buffer` is currently used, instead of `StagingBelt::write_buffer` which would solve this.

I started working on a fix in this PR yesterday: #1133
To have staging belt and command encoder available in all these places we have to refactor both (the latter together with the frame context holding it) into the `WgpuContext` that each canvas holds a copy of. That's the next thing to solve...

**Comment by nobbele** [comment] 2022-12-01 16:29
supposedly *not* a duplicate of https://github.com/ggez/ggez/issues/1129 but should be fixed in https://github.com/ggez/ggez/pull/1139

**Comment by nobbele** [comment] 2022-12-03 17:05
should be solved

**Closed by nobbele** 2022-12-03 17:05 UTC
Labels: bug, Type-CODE
